package au.com.leighton.portal.peoplefinder.model;

import java.util.ArrayList;
import java.util.List;

import oracle.jbo.server.ViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 30 10:48:07 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WcPeopleConnProfilePhotoViewImpl extends ViewObjectImpl
{
    /**
     * This is the default constructor (do not remove).
     */
    public WcPeopleConnProfilePhotoViewImpl()
    {
    }

    /**
     * Returns the bind variable value for userguid.
     * @return bind variable value for userguid
     */
    public String getuserguid()
    {
        return (String)getNamedWhereClauseParam("userguid");
    }

    /**
     * Sets <code>value</code> for bind variable userguid.
     * @param value value to bind as userguid
     */
    public void setuserguid(String value)
    {
        setNamedWhereClauseParam("userguid", value);
    }

    /**
     * Returns the bind variable value for photosize.
     * @return bind variable value for photosize
     */
    public String getphotosize()
    {
        return (String)getNamedWhereClauseParam("photosize");
    }

    /**
     * Sets <code>value</code> for bind variable photosize.
     * @param value value to bind as photosize
     */
    public void setphotosize(String value)
    {
        setNamedWhereClauseParam("photosize", value);
    }

    public List<ActorPhoto> getPhotosForUserGuidId(String userGuid,
                                                   String photoSize)
    {
        List<ActorPhoto> result = new ArrayList<ActorPhoto>();

        setuserguid(userGuid);
        setphotosize(photoSize);

        executeQuery();

        WcPeopleConnProfilePhotoViewRowImpl row = null;

        while ((row = (WcPeopleConnProfilePhotoViewRowImpl)next()) != null)
        {
            result.add(row.toBean());
        }

        return result;
    }
}
