package au.com.leighton.portal.peoplefinder.model;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 30 10:46:57 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WcPeopleConnConnectionCollImpl extends EntityCache
{
    /**
     * This is the default constructor (do not remove).
     */
    public WcPeopleConnConnectionCollImpl()
    {
    }
}
