package au.com.leighton.portal.peoplefinder.model;

import oracle.jbo.Key;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 30 10:47:05 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WcPeopleConnProfilePhotoImpl extends EntityImpl
{
    private static WcPeopleConnProfilePhotoDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum
    {
        Id
        {
            public Object get(WcPeopleConnProfilePhotoImpl obj)
            {
                return obj.getId();
            }

            public void put(WcPeopleConnProfilePhotoImpl obj, Object value)
            {
                obj.setId((String)value);
            }
        }
        ,
        UserGuid
        {
            public Object get(WcPeopleConnProfilePhotoImpl obj)
            {
                return obj.getUserGuid();
            }

            public void put(WcPeopleConnProfilePhotoImpl obj, Object value)
            {
                obj.setUserGuid((String)value);
            }
        }
        ,
        PhotoSize
        {
            public Object get(WcPeopleConnProfilePhotoImpl obj)
            {
                return obj.getPhotoSize();
            }

            public void put(WcPeopleConnProfilePhotoImpl obj, Object value)
            {
                obj.setPhotoSize((String)value);
            }
        }
        ,
        ImageData
        {
            public Object get(WcPeopleConnProfilePhotoImpl obj)
            {
                return obj.getImageData();
            }

            public void put(WcPeopleConnProfilePhotoImpl obj, Object value)
            {
                obj.setImageData((BlobDomain)value);
            }
        }
        ,
        Version
        {
            public Object get(WcPeopleConnProfilePhotoImpl obj)
            {
                return obj.getVersion();
            }

            public void put(WcPeopleConnProfilePhotoImpl obj, Object value)
            {
                obj.setVersion((Number)value);
            }
        }
        ,
        ApplicationId
        {
            public Object get(WcPeopleConnProfilePhotoImpl obj)
            {
                return obj.getApplicationId();
            }

            public void put(WcPeopleConnProfilePhotoImpl obj, Object value)
            {
                obj.setApplicationId((String)value);
            }
        }
        ,
        EnterpriseId
        {
            public Object get(WcPeopleConnProfilePhotoImpl obj)
            {
                return obj.getEnterpriseId();
            }

            public void put(WcPeopleConnProfilePhotoImpl obj, Object value)
            {
                obj.setEnterpriseId((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(WcPeopleConnProfilePhotoImpl object);

        public abstract void put(WcPeopleConnProfilePhotoImpl object,
                                 Object value);

        public int index()
        {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex()
        {
            return firstIndex;
        }

        public static int count()
        {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues()
        {
            if (vals == null)
            {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ID = AttributesEnum.Id.index();
    public static final int USERGUID = AttributesEnum.UserGuid.index();
    public static final int PHOTOSIZE = AttributesEnum.PhotoSize.index();
    public static final int IMAGEDATA = AttributesEnum.ImageData.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int APPLICATIONID = AttributesEnum.ApplicationId.index();
    public static final int ENTERPRISEID = AttributesEnum.EnterpriseId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public WcPeopleConnProfilePhotoImpl()
    {
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the Id
     */
    public String getId()
    {
        return (String)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(String value)
    {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for UserGuid, using the alias name UserGuid.
     * @return the UserGuid
     */
    public String getUserGuid()
    {
        return (String)getAttributeInternal(USERGUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserGuid.
     * @param value value to set the UserGuid
     */
    public void setUserGuid(String value)
    {
        setAttributeInternal(USERGUID, value);
    }

    /**
     * Gets the attribute value for PhotoSize, using the alias name PhotoSize.
     * @return the PhotoSize
     */
    public String getPhotoSize()
    {
        return (String)getAttributeInternal(PHOTOSIZE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PhotoSize.
     * @param value value to set the PhotoSize
     */
    public void setPhotoSize(String value)
    {
        setAttributeInternal(PHOTOSIZE, value);
    }

    /**
     * Gets the attribute value for ImageData, using the alias name ImageData.
     * @return the ImageData
     */
    public BlobDomain getImageData()
    {
        return (BlobDomain)getAttributeInternal(IMAGEDATA);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImageData.
     * @param value value to set the ImageData
     */
    public void setImageData(BlobDomain value)
    {
        setAttributeInternal(IMAGEDATA, value);
    }

    /**
     * Gets the attribute value for Version, using the alias name Version.
     * @return the Version
     */
    public Number getVersion()
    {
        return (Number)getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Version.
     * @param value value to set the Version
     */
    public void setVersion(Number value)
    {
        setAttributeInternal(VERSION, value);
    }

    /**
     * Gets the attribute value for ApplicationId, using the alias name ApplicationId.
     * @return the ApplicationId
     */
    public String getApplicationId()
    {
        return (String)getAttributeInternal(APPLICATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApplicationId.
     * @param value value to set the ApplicationId
     */
    public void setApplicationId(String value)
    {
        setAttributeInternal(APPLICATIONID, value);
    }

    /**
     * Gets the attribute value for EnterpriseId, using the alias name EnterpriseId.
     * @return the EnterpriseId
     */
    public Number getEnterpriseId()
    {
        return (Number)getAttributeInternal(ENTERPRISEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EnterpriseId.
     * @param value value to set the EnterpriseId
     */
    public void setEnterpriseId(Number value)
    {
        setAttributeInternal(ENTERPRISEID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception
    {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count()))
        {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception
    {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count()))
        {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String id)
    {
        return new Key(new Object[]{id});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject()
    {
        if (mDefinitionObject == null)
        {
            mDefinitionObject = (WcPeopleConnProfilePhotoDefImpl)EntityDefImpl.findDefObject("au.com.leighton.portal.peoplefinder.model.WcPeopleConnProfilePhoto");
        }
        return mDefinitionObject;
    }
}
