package au.com.leighton.portal.peoplefinder.model;

import java.util.ArrayList;
import java.util.List;

import oracle.jbo.server.ViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 30 10:47:59 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WcPeopleConnConnectionViewImpl extends ViewObjectImpl
{
    /**
     * This is the default constructor (do not remove).
     */
    public WcPeopleConnConnectionViewImpl()
    {
    }

    /**
     * Returns the bind variable value for ownerid.
     * @return bind variable value for ownerid
     */
    public String getownerid()
    {
        return (String)getNamedWhereClauseParam("ownerid");
    }

    /**
     * Sets <code>value</code> for bind variable ownerid.
     * @param value value to bind as ownerid
     */
    public void setownerid(String value)
    {
        setNamedWhereClauseParam("ownerid", value);
    }

    public List<PeopleConnection> getConnectionsForOwnerId(String ownerId)
    {
        List<PeopleConnection> result = new ArrayList<PeopleConnection>();

        setownerid(ownerId);

        executeQuery();

        WcPeopleConnConnectionViewRowImpl row = null;

        while ((row = (WcPeopleConnConnectionViewRowImpl)next()) != null)
        {
            result.add(row.toBean());
        }

        return result;
    }
}
