package au.com.leighton.portal.peoplefinder.model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 30 10:48:20 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WcSpaceHeaderViewImpl extends ViewObjectImpl
{
    /**
     * This is the default constructor (do not remove).
     */
    public WcSpaceHeaderViewImpl()
    {
    }

    /**
     * Returns the bind variable value for spaceid.
     * @return bind variable value for spaceid
     */
    public String getspaceid()
    {
        return (String)getNamedWhereClauseParam("spaceid");
    }

    /**
     * Sets <code>value</code> for bind variable spaceid.
     * @param value value to bind as spaceid
     */
    public void setspaceid(String value)
    {
        setNamedWhereClauseParam("spaceid", value);
    }

    public SpaceHeader getHeaderForSpace(Space space)
    {
        SpaceHeader result = null;

        if (space != null)
        {
            setspaceid(space.getSpaceId());

            executeQuery();

            WcSpaceHeaderViewRowImpl currentRow = null;

            if ((currentRow = (WcSpaceHeaderViewRowImpl)next()) != null)
            {
                result = currentRow.toBean();
            }
        }

        return result;
    }
}
