package au.com.leighton.portal.peoplefinder.model;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 30 10:47:16 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WcSpaceHeaderImpl extends EntityImpl
{
    private static WcSpaceHeaderDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum
    {
        ApplicationId
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getApplicationId();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setApplicationId((String)value);
            }
        }
        ,
        SpaceGuid
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getSpaceGuid();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setSpaceGuid((String)value);
            }
        }
        ,
        SpaceId
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getSpaceId();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setSpaceId((String)value);
            }
        }
        ,
        DisplayName
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getDisplayName();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setDisplayName((String)value);
            }
        }
        ,
        Description
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getDescription();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setDescription((String)value);
            }
        }
        ,
        SpacePublic
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getSpacePublic();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setSpacePublic((String)value);
            }
        }
        ,
        SpacesUser
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getSpacesUser();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setSpacesUser((String)value);
            }
        }
        ,
        Discoverable
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getDiscoverable();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setDiscoverable((String)value);
            }
        }
        ,
        SpaceOffline
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getSpaceOffline();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setSpaceOffline((String)value);
            }
        }
        ,
        Closed
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getClosed();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setClosed((String)value);
            }
        }
        ,
        SelfSubEnabled
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getSelfSubEnabled();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setSelfSubEnabled((String)value);
            }
        }
        ,
        RssEnabled
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getRssEnabled();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setRssEnabled((String)value);
            }
        }
        ,
        SpacesType
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getSpacesType();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setSpacesType((String)value);
            }
        }
        ,
        Version
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getVersion();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setVersion((Number)value);
            }
        }
        ,
        Icon
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getIcon();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setIcon((String)value);
            }
        }
        ,
        Logo
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getLogo();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setLogo((String)value);
            }
        }
        ,
        Keywords
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getKeywords();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setKeywords((String)value);
            }
        }
        ,
        CreatedBy
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getCreatedBy();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        CreateDate
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getCreateDate();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setCreateDate((Timestamp)value);
            }
        }
        ,
        UpdatedBy
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getUpdatedBy();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setUpdatedBy((String)value);
            }
        }
        ,
        LastUpdateDate
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getLastUpdateDate();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setLastUpdateDate((Timestamp)value);
            }
        }
        ,
        ParentGuid
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getParentGuid();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setParentGuid((String)value);
            }
        }
        ,
        SecurityParentGuid
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getSecurityParentGuid();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setSecurityParentGuid((String)value);
            }
        }
        ,
        AncestorPath
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getAncestorPath();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setAncestorPath((String)value);
            }
        }
        ,
        IsSeeded
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getIsSeeded();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setIsSeeded((String)value);
            }
        }
        ,
        SubGsCount
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getSubGsCount();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setSubGsCount((Number)value);
            }
        }
        ,
        GsMemberCount
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getGsMemberCount();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setGsMemberCount((Number)value);
            }
        }
        ,
        EnterpriseId
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getEnterpriseId();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setEnterpriseId((Number)value);
            }
        }
        ,
        WcSpaceHeader
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getWcSpaceHeader();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        WcSpaceHeader1
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getWcSpaceHeader1();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setWcSpaceHeader1((WcSpaceHeaderImpl)value);
            }
        }
        ,
        WcSpaceHeader3
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getWcSpaceHeader3();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        WcSpaceHeader2
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getWcSpaceHeader2();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setWcSpaceHeader2((WcSpaceHeaderImpl)value);
            }
        }
        ,
        WcSpaceUsrDetail
        {
            public Object get(WcSpaceHeaderImpl obj)
            {
                return obj.getWcSpaceUsrDetail();
            }

            public void put(WcSpaceHeaderImpl obj, Object value)
            {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(WcSpaceHeaderImpl object);

        public abstract void put(WcSpaceHeaderImpl object, Object value);

        public int index()
        {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex()
        {
            return firstIndex;
        }

        public static int count()
        {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues()
        {
            if (vals == null)
            {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int APPLICATIONID = AttributesEnum.ApplicationId.index();
    public static final int SPACEGUID = AttributesEnum.SpaceGuid.index();
    public static final int SPACEID = AttributesEnum.SpaceId.index();
    public static final int DISPLAYNAME = AttributesEnum.DisplayName.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int SPACEPUBLIC = AttributesEnum.SpacePublic.index();
    public static final int SPACESUSER = AttributesEnum.SpacesUser.index();
    public static final int DISCOVERABLE = AttributesEnum.Discoverable.index();
    public static final int SPACEOFFLINE = AttributesEnum.SpaceOffline.index();
    public static final int CLOSED = AttributesEnum.Closed.index();
    public static final int SELFSUBENABLED = AttributesEnum.SelfSubEnabled.index();
    public static final int RSSENABLED = AttributesEnum.RssEnabled.index();
    public static final int SPACESTYPE = AttributesEnum.SpacesType.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int ICON = AttributesEnum.Icon.index();
    public static final int LOGO = AttributesEnum.Logo.index();
    public static final int KEYWORDS = AttributesEnum.Keywords.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDATE = AttributesEnum.CreateDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int PARENTGUID = AttributesEnum.ParentGuid.index();
    public static final int SECURITYPARENTGUID = AttributesEnum.SecurityParentGuid.index();
    public static final int ANCESTORPATH = AttributesEnum.AncestorPath.index();
    public static final int ISSEEDED = AttributesEnum.IsSeeded.index();
    public static final int SUBGSCOUNT = AttributesEnum.SubGsCount.index();
    public static final int GSMEMBERCOUNT = AttributesEnum.GsMemberCount.index();
    public static final int ENTERPRISEID = AttributesEnum.EnterpriseId.index();
    public static final int WCSPACEHEADER = AttributesEnum.WcSpaceHeader.index();
    public static final int WCSPACEHEADER1 = AttributesEnum.WcSpaceHeader1.index();
    public static final int WCSPACEHEADER3 = AttributesEnum.WcSpaceHeader3.index();
    public static final int WCSPACEHEADER2 = AttributesEnum.WcSpaceHeader2.index();
    public static final int WCSPACEUSRDETAIL = AttributesEnum.WcSpaceUsrDetail.index();

    /**
     * This is the default constructor (do not remove).
     */
    public WcSpaceHeaderImpl()
    {
    }

    /**
     * Gets the attribute value for ApplicationId, using the alias name ApplicationId.
     * @return the ApplicationId
     */
    public String getApplicationId()
    {
        return (String)getAttributeInternal(APPLICATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApplicationId.
     * @param value value to set the ApplicationId
     */
    public void setApplicationId(String value)
    {
        setAttributeInternal(APPLICATIONID, value);
    }

    /**
     * Gets the attribute value for SpaceGuid, using the alias name SpaceGuid.
     * @return the SpaceGuid
     */
    public String getSpaceGuid()
    {
        return (String)getAttributeInternal(SPACEGUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SpaceGuid.
     * @param value value to set the SpaceGuid
     */
    public void setSpaceGuid(String value)
    {
        setAttributeInternal(SPACEGUID, value);
    }

    /**
     * Gets the attribute value for SpaceId, using the alias name SpaceId.
     * @return the SpaceId
     */
    public String getSpaceId()
    {
        return (String)getAttributeInternal(SPACEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SpaceId.
     * @param value value to set the SpaceId
     */
    public void setSpaceId(String value)
    {
        setAttributeInternal(SPACEID, value);
    }

    /**
     * Gets the attribute value for DisplayName, using the alias name DisplayName.
     * @return the DisplayName
     */
    public String getDisplayName()
    {
        return (String)getAttributeInternal(DISPLAYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for DisplayName.
     * @param value value to set the DisplayName
     */
    public void setDisplayName(String value)
    {
        setAttributeInternal(DISPLAYNAME, value);
    }

    /**
     * Gets the attribute value for Description, using the alias name Description.
     * @return the Description
     */
    public String getDescription()
    {
        return (String)getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Description.
     * @param value value to set the Description
     */
    public void setDescription(String value)
    {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for SpacePublic, using the alias name SpacePublic.
     * @return the SpacePublic
     */
    public String getSpacePublic()
    {
        return (String)getAttributeInternal(SPACEPUBLIC);
    }

    /**
     * Sets <code>value</code> as the attribute value for SpacePublic.
     * @param value value to set the SpacePublic
     */
    public void setSpacePublic(String value)
    {
        setAttributeInternal(SPACEPUBLIC, value);
    }

    /**
     * Gets the attribute value for SpacesUser, using the alias name SpacesUser.
     * @return the SpacesUser
     */
    public String getSpacesUser()
    {
        return (String)getAttributeInternal(SPACESUSER);
    }

    /**
     * Sets <code>value</code> as the attribute value for SpacesUser.
     * @param value value to set the SpacesUser
     */
    public void setSpacesUser(String value)
    {
        setAttributeInternal(SPACESUSER, value);
    }

    /**
     * Gets the attribute value for Discoverable, using the alias name Discoverable.
     * @return the Discoverable
     */
    public String getDiscoverable()
    {
        return (String)getAttributeInternal(DISCOVERABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Discoverable.
     * @param value value to set the Discoverable
     */
    public void setDiscoverable(String value)
    {
        setAttributeInternal(DISCOVERABLE, value);
    }

    /**
     * Gets the attribute value for SpaceOffline, using the alias name SpaceOffline.
     * @return the SpaceOffline
     */
    public String getSpaceOffline()
    {
        return (String)getAttributeInternal(SPACEOFFLINE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SpaceOffline.
     * @param value value to set the SpaceOffline
     */
    public void setSpaceOffline(String value)
    {
        setAttributeInternal(SPACEOFFLINE, value);
    }

    /**
     * Gets the attribute value for Closed, using the alias name Closed.
     * @return the Closed
     */
    public String getClosed()
    {
        return (String)getAttributeInternal(CLOSED);
    }

    /**
     * Sets <code>value</code> as the attribute value for Closed.
     * @param value value to set the Closed
     */
    public void setClosed(String value)
    {
        setAttributeInternal(CLOSED, value);
    }

    /**
     * Gets the attribute value for SelfSubEnabled, using the alias name SelfSubEnabled.
     * @return the SelfSubEnabled
     */
    public String getSelfSubEnabled()
    {
        return (String)getAttributeInternal(SELFSUBENABLED);
    }

    /**
     * Sets <code>value</code> as the attribute value for SelfSubEnabled.
     * @param value value to set the SelfSubEnabled
     */
    public void setSelfSubEnabled(String value)
    {
        setAttributeInternal(SELFSUBENABLED, value);
    }

    /**
     * Gets the attribute value for RssEnabled, using the alias name RssEnabled.
     * @return the RssEnabled
     */
    public String getRssEnabled()
    {
        return (String)getAttributeInternal(RSSENABLED);
    }

    /**
     * Sets <code>value</code> as the attribute value for RssEnabled.
     * @param value value to set the RssEnabled
     */
    public void setRssEnabled(String value)
    {
        setAttributeInternal(RSSENABLED, value);
    }

    /**
     * Gets the attribute value for SpacesType, using the alias name SpacesType.
     * @return the SpacesType
     */
    public String getSpacesType()
    {
        return (String)getAttributeInternal(SPACESTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SpacesType.
     * @param value value to set the SpacesType
     */
    public void setSpacesType(String value)
    {
        setAttributeInternal(SPACESTYPE, value);
    }

    /**
     * Gets the attribute value for Version, using the alias name Version.
     * @return the Version
     */
    public Number getVersion()
    {
        return (Number)getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Version.
     * @param value value to set the Version
     */
    public void setVersion(Number value)
    {
        setAttributeInternal(VERSION, value);
    }

    /**
     * Gets the attribute value for Icon, using the alias name Icon.
     * @return the Icon
     */
    public String getIcon()
    {
        return (String)getAttributeInternal(ICON);
    }

    /**
     * Sets <code>value</code> as the attribute value for Icon.
     * @param value value to set the Icon
     */
    public void setIcon(String value)
    {
        setAttributeInternal(ICON, value);
    }

    /**
     * Gets the attribute value for Logo, using the alias name Logo.
     * @return the Logo
     */
    public String getLogo()
    {
        return (String)getAttributeInternal(LOGO);
    }

    /**
     * Sets <code>value</code> as the attribute value for Logo.
     * @param value value to set the Logo
     */
    public void setLogo(String value)
    {
        setAttributeInternal(LOGO, value);
    }

    /**
     * Gets the attribute value for Keywords, using the alias name Keywords.
     * @return the Keywords
     */
    public String getKeywords()
    {
        return (String)getAttributeInternal(KEYWORDS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Keywords.
     * @param value value to set the Keywords
     */
    public void setKeywords(String value)
    {
        setAttributeInternal(KEYWORDS, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy()
    {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value)
    {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreateDate, using the alias name CreateDate.
     * @return the CreateDate
     */
    public Timestamp getCreateDate()
    {
        return (Timestamp)getAttributeInternal(CREATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreateDate.
     * @param value value to set the CreateDate
     */
    public void setCreateDate(Timestamp value)
    {
        setAttributeInternal(CREATEDATE, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the UpdatedBy
     */
    public String getUpdatedBy()
    {
        return (String)getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(String value)
    {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Timestamp getLastUpdateDate()
    {
        return (Timestamp)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Timestamp value)
    {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for ParentGuid, using the alias name ParentGuid.
     * @return the ParentGuid
     */
    public String getParentGuid()
    {
        return (String)getAttributeInternal(PARENTGUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParentGuid.
     * @param value value to set the ParentGuid
     */
    public void setParentGuid(String value)
    {
        setAttributeInternal(PARENTGUID, value);
    }

    /**
     * Gets the attribute value for SecurityParentGuid, using the alias name SecurityParentGuid.
     * @return the SecurityParentGuid
     */
    public String getSecurityParentGuid()
    {
        return (String)getAttributeInternal(SECURITYPARENTGUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SecurityParentGuid.
     * @param value value to set the SecurityParentGuid
     */
    public void setSecurityParentGuid(String value)
    {
        setAttributeInternal(SECURITYPARENTGUID, value);
    }

    /**
     * Gets the attribute value for AncestorPath, using the alias name AncestorPath.
     * @return the AncestorPath
     */
    public String getAncestorPath()
    {
        return (String)getAttributeInternal(ANCESTORPATH);
    }

    /**
     * Sets <code>value</code> as the attribute value for AncestorPath.
     * @param value value to set the AncestorPath
     */
    public void setAncestorPath(String value)
    {
        setAttributeInternal(ANCESTORPATH, value);
    }

    /**
     * Gets the attribute value for IsSeeded, using the alias name IsSeeded.
     * @return the IsSeeded
     */
    public String getIsSeeded()
    {
        return (String)getAttributeInternal(ISSEEDED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsSeeded.
     * @param value value to set the IsSeeded
     */
    public void setIsSeeded(String value)
    {
        setAttributeInternal(ISSEEDED, value);
    }

    /**
     * Gets the attribute value for SubGsCount, using the alias name SubGsCount.
     * @return the SubGsCount
     */
    public Number getSubGsCount()
    {
        return (Number)getAttributeInternal(SUBGSCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for SubGsCount.
     * @param value value to set the SubGsCount
     */
    public void setSubGsCount(Number value)
    {
        setAttributeInternal(SUBGSCOUNT, value);
    }

    /**
     * Gets the attribute value for GsMemberCount, using the alias name GsMemberCount.
     * @return the GsMemberCount
     */
    public Number getGsMemberCount()
    {
        return (Number)getAttributeInternal(GSMEMBERCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for GsMemberCount.
     * @param value value to set the GsMemberCount
     */
    public void setGsMemberCount(Number value)
    {
        setAttributeInternal(GSMEMBERCOUNT, value);
    }

    /**
     * Gets the attribute value for EnterpriseId, using the alias name EnterpriseId.
     * @return the EnterpriseId
     */
    public Number getEnterpriseId()
    {
        return (Number)getAttributeInternal(ENTERPRISEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EnterpriseId.
     * @param value value to set the EnterpriseId
     */
    public void setEnterpriseId(Number value)
    {
        setAttributeInternal(ENTERPRISEID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception
    {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count()))
        {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception
    {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count()))
        {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getWcSpaceHeader()
    {
        return (RowIterator)getAttributeInternal(WCSPACEHEADER);
    }

    /**
     * @return the associated entity WcSpaceHeaderImpl.
     */
    public WcSpaceHeaderImpl getWcSpaceHeader1()
    {
        return (WcSpaceHeaderImpl)getAttributeInternal(WCSPACEHEADER1);
    }

    /**
     * Sets <code>value</code> as the associated entity WcSpaceHeaderImpl.
     */
    public void setWcSpaceHeader1(WcSpaceHeaderImpl value)
    {
        setAttributeInternal(WCSPACEHEADER1, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getWcSpaceHeader3()
    {
        return (RowIterator)getAttributeInternal(WCSPACEHEADER3);
    }

    /**
     * @return the associated entity WcSpaceHeaderImpl.
     */
    public WcSpaceHeaderImpl getWcSpaceHeader2()
    {
        return (WcSpaceHeaderImpl)getAttributeInternal(WCSPACEHEADER2);
    }

    /**
     * Sets <code>value</code> as the associated entity WcSpaceHeaderImpl.
     */
    public void setWcSpaceHeader2(WcSpaceHeaderImpl value)
    {
        setAttributeInternal(WCSPACEHEADER2, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getWcSpaceUsrDetail()
    {
        return (RowIterator)getAttributeInternal(WCSPACEUSRDETAIL);
    }

    /**
     * @param applicationId key constituent
     * @param spaceGuid key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String applicationId, String spaceGuid)
    {
        return new Key(new Object[]{applicationId, spaceGuid});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject()
    {
        if (mDefinitionObject == null)
        {
            mDefinitionObject = (WcSpaceHeaderDefImpl)EntityDefImpl.findDefObject("au.com.leighton.portal.peoplefinder.model.WcSpaceHeader");
        }
        return mDefinitionObject;
    }
}
