package au.com.leighton.portal.peoplefinder.model;

import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 30 10:48:20 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WcSpaceHeaderViewRowImpl extends ViewRowImpl
{
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum
    {
        ApplicationId
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getApplicationId();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setApplicationId((String)value);
            }
        },
        SpaceGuid
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getSpaceGuid();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setSpaceGuid((String)value);
            }
        },
        SpaceId
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getSpaceId();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setSpaceId((String)value);
            }
        },
        DisplayName
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getDisplayName();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setDisplayName((String)value);
            }
        },
        Description
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getDescription();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setDescription((String)value);
            }
        },
        SpacePublic
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getSpacePublic();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setSpacePublic((String)value);
            }
        },
        SpacesUser
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getSpacesUser();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setSpacesUser((String)value);
            }
        },
        Discoverable
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getDiscoverable();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setDiscoverable((String)value);
            }
        },
        SpaceOffline
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getSpaceOffline();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setSpaceOffline((String)value);
            }
        },
        Closed
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getClosed();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setClosed((String)value);
            }
        },
        SelfSubEnabled
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getSelfSubEnabled();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setSelfSubEnabled((String)value);
            }
        },
        RssEnabled
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getRssEnabled();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setRssEnabled((String)value);
            }
        },
        SpacesType
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getSpacesType();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setSpacesType((String)value);
            }
        },
        Version
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getVersion();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setVersion((Number)value);
            }
        },
        Icon
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getIcon();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setIcon((String)value);
            }
        },
        Logo
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getLogo();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setLogo((String)value);
            }
        },
        Keywords
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getKeywords();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setKeywords((String)value);
            }
        },
        CreatedBy
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getCreatedBy();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setCreatedBy((String)value);
            }
        },
        CreateDate
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getCreateDate();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setCreateDate((Timestamp)value);
            }
        },
        UpdatedBy
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getUpdatedBy();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setUpdatedBy((String)value);
            }
        },
        LastUpdateDate
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getLastUpdateDate();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setLastUpdateDate((Timestamp)value);
            }
        },
        ParentGuid
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getParentGuid();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setParentGuid((String)value);
            }
        },
        SecurityParentGuid
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getSecurityParentGuid();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setSecurityParentGuid((String)value);
            }
        },
        AncestorPath
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getAncestorPath();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setAncestorPath((String)value);
            }
        },
        IsSeeded
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getIsSeeded();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setIsSeeded((String)value);
            }
        },
        SubGsCount
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getSubGsCount();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setSubGsCount((Number)value);
            }
        },
        GsMemberCount
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getGsMemberCount();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setGsMemberCount((Number)value);
            }
        },
        EnterpriseId
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getEnterpriseId();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setEnterpriseId((Number)value);
            }
        },
        WcSpaceUsrDetailView
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getWcSpaceUsrDetailView();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setAttributeInternal(index(), value);
            }
        },
        ApplicationIdWcSpaceHeaderView
        {
            public Object get(WcSpaceHeaderViewRowImpl obj)
            {
                return obj.getApplicationIdWcSpaceHeaderView();
            }

            public void put(WcSpaceHeaderViewRowImpl obj, Object value)
            {
                obj.setAttributeInternal(index(), value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(WcSpaceHeaderViewRowImpl object);

        public abstract void put(WcSpaceHeaderViewRowImpl object,
                                 Object value);

        public int index()
        {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex()
        {
            return firstIndex;
        }

        public static int count()
        {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues()
        {
            if (vals == null)
            {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int APPLICATIONID =
        AttributesEnum.ApplicationId.index();
    public static final int SPACEGUID = AttributesEnum.SpaceGuid.index();
    public static final int SPACEID = AttributesEnum.SpaceId.index();
    public static final int DISPLAYNAME = AttributesEnum.DisplayName.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int SPACEPUBLIC = AttributesEnum.SpacePublic.index();
    public static final int SPACESUSER = AttributesEnum.SpacesUser.index();
    public static final int DISCOVERABLE = AttributesEnum.Discoverable.index();
    public static final int SPACEOFFLINE = AttributesEnum.SpaceOffline.index();
    public static final int CLOSED = AttributesEnum.Closed.index();
    public static final int SELFSUBENABLED =
        AttributesEnum.SelfSubEnabled.index();
    public static final int RSSENABLED = AttributesEnum.RssEnabled.index();
    public static final int SPACESTYPE = AttributesEnum.SpacesType.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int ICON = AttributesEnum.Icon.index();
    public static final int LOGO = AttributesEnum.Logo.index();
    public static final int KEYWORDS = AttributesEnum.Keywords.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDATE = AttributesEnum.CreateDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int LASTUPDATEDATE =
        AttributesEnum.LastUpdateDate.index();
    public static final int PARENTGUID = AttributesEnum.ParentGuid.index();
    public static final int SECURITYPARENTGUID =
        AttributesEnum.SecurityParentGuid.index();
    public static final int ANCESTORPATH = AttributesEnum.AncestorPath.index();
    public static final int ISSEEDED = AttributesEnum.IsSeeded.index();
    public static final int SUBGSCOUNT = AttributesEnum.SubGsCount.index();
    public static final int GSMEMBERCOUNT =
        AttributesEnum.GsMemberCount.index();
    public static final int ENTERPRISEID = AttributesEnum.EnterpriseId.index();
    public static final int WCSPACEUSRDETAILVIEW =
        AttributesEnum.WcSpaceUsrDetailView.index();
    public static final int APPLICATIONIDWCSPACEHEADERVIEW =
        AttributesEnum.ApplicationIdWcSpaceHeaderView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public WcSpaceHeaderViewRowImpl()
    {
    }

    /**
     * Gets the attribute value for the calculated attribute ApplicationId.
     * @return the ApplicationId
     */
    public String getApplicationId()
    {
        return (String)getAttributeInternal(APPLICATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ApplicationId.
     * @param value value to set the  ApplicationId
     */
    public void setApplicationId(String value)
    {
        setAttributeInternal(APPLICATIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SpaceGuid.
     * @return the SpaceGuid
     */
    public String getSpaceGuid()
    {
        return (String)getAttributeInternal(SPACEGUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SpaceGuid.
     * @param value value to set the  SpaceGuid
     */
    public void setSpaceGuid(String value)
    {
        setAttributeInternal(SPACEGUID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SpaceId.
     * @return the SpaceId
     */
    public String getSpaceId()
    {
        return (String)getAttributeInternal(SPACEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SpaceId.
     * @param value value to set the  SpaceId
     */
    public void setSpaceId(String value)
    {
        setAttributeInternal(SPACEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DisplayName.
     * @return the DisplayName
     */
    public String getDisplayName()
    {
        return (String)getAttributeInternal(DISPLAYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DisplayName.
     * @param value value to set the  DisplayName
     */
    public void setDisplayName(String value)
    {
        setAttributeInternal(DISPLAYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Description.
     * @return the Description
     */
    public String getDescription()
    {
        return (String)getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Description.
     * @param value value to set the  Description
     */
    public void setDescription(String value)
    {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SpacePublic.
     * @return the SpacePublic
     */
    public String getSpacePublic()
    {
        return (String)getAttributeInternal(SPACEPUBLIC);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SpacePublic.
     * @param value value to set the  SpacePublic
     */
    public void setSpacePublic(String value)
    {
        setAttributeInternal(SPACEPUBLIC, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SpacesUser.
     * @return the SpacesUser
     */
    public String getSpacesUser()
    {
        return (String)getAttributeInternal(SPACESUSER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SpacesUser.
     * @param value value to set the  SpacesUser
     */
    public void setSpacesUser(String value)
    {
        setAttributeInternal(SPACESUSER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Discoverable.
     * @return the Discoverable
     */
    public String getDiscoverable()
    {
        return (String)getAttributeInternal(DISCOVERABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Discoverable.
     * @param value value to set the  Discoverable
     */
    public void setDiscoverable(String value)
    {
        setAttributeInternal(DISCOVERABLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SpaceOffline.
     * @return the SpaceOffline
     */
    public String getSpaceOffline()
    {
        return (String)getAttributeInternal(SPACEOFFLINE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SpaceOffline.
     * @param value value to set the  SpaceOffline
     */
    public void setSpaceOffline(String value)
    {
        setAttributeInternal(SPACEOFFLINE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Closed.
     * @return the Closed
     */
    public String getClosed()
    {
        return (String)getAttributeInternal(CLOSED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Closed.
     * @param value value to set the  Closed
     */
    public void setClosed(String value)
    {
        setAttributeInternal(CLOSED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SelfSubEnabled.
     * @return the SelfSubEnabled
     */
    public String getSelfSubEnabled()
    {
        return (String)getAttributeInternal(SELFSUBENABLED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SelfSubEnabled.
     * @param value value to set the  SelfSubEnabled
     */
    public void setSelfSubEnabled(String value)
    {
        setAttributeInternal(SELFSUBENABLED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RssEnabled.
     * @return the RssEnabled
     */
    public String getRssEnabled()
    {
        return (String)getAttributeInternal(RSSENABLED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RssEnabled.
     * @param value value to set the  RssEnabled
     */
    public void setRssEnabled(String value)
    {
        setAttributeInternal(RSSENABLED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SpacesType.
     * @return the SpacesType
     */
    public String getSpacesType()
    {
        return (String)getAttributeInternal(SPACESTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SpacesType.
     * @param value value to set the  SpacesType
     */
    public void setSpacesType(String value)
    {
        setAttributeInternal(SPACESTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Version.
     * @return the Version
     */
    public Number getVersion()
    {
        return (Number)getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Version.
     * @param value value to set the  Version
     */
    public void setVersion(Number value)
    {
        setAttributeInternal(VERSION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Icon.
     * @return the Icon
     */
    public String getIcon()
    {
        return (String)getAttributeInternal(ICON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Icon.
     * @param value value to set the  Icon
     */
    public void setIcon(String value)
    {
        setAttributeInternal(ICON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Logo.
     * @return the Logo
     */
    public String getLogo()
    {
        return (String)getAttributeInternal(LOGO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Logo.
     * @param value value to set the  Logo
     */
    public void setLogo(String value)
    {
        setAttributeInternal(LOGO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Keywords.
     * @return the Keywords
     */
    public String getKeywords()
    {
        return (String)getAttributeInternal(KEYWORDS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Keywords.
     * @param value value to set the  Keywords
     */
    public void setKeywords(String value)
    {
        setAttributeInternal(KEYWORDS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy()
    {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy.
     * @param value value to set the  CreatedBy
     */
    public void setCreatedBy(String value)
    {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreateDate.
     * @return the CreateDate
     */
    public Timestamp getCreateDate()
    {
        return (Timestamp)getAttributeInternal(CREATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreateDate.
     * @param value value to set the  CreateDate
     */
    public void setCreateDate(Timestamp value)
    {
        setAttributeInternal(CREATEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UpdatedBy.
     * @return the UpdatedBy
     */
    public String getUpdatedBy()
    {
        return (String)getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UpdatedBy.
     * @param value value to set the  UpdatedBy
     */
    public void setUpdatedBy(String value)
    {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Timestamp getLastUpdateDate()
    {
        return (Timestamp)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate.
     * @param value value to set the  LastUpdateDate
     */
    public void setLastUpdateDate(Timestamp value)
    {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ParentGuid.
     * @return the ParentGuid
     */
    public String getParentGuid()
    {
        return (String)getAttributeInternal(PARENTGUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ParentGuid.
     * @param value value to set the  ParentGuid
     */
    public void setParentGuid(String value)
    {
        setAttributeInternal(PARENTGUID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SecurityParentGuid.
     * @return the SecurityParentGuid
     */
    public String getSecurityParentGuid()
    {
        return (String)getAttributeInternal(SECURITYPARENTGUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SecurityParentGuid.
     * @param value value to set the  SecurityParentGuid
     */
    public void setSecurityParentGuid(String value)
    {
        setAttributeInternal(SECURITYPARENTGUID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute AncestorPath.
     * @return the AncestorPath
     */
    public String getAncestorPath()
    {
        return (String)getAttributeInternal(ANCESTORPATH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute AncestorPath.
     * @param value value to set the  AncestorPath
     */
    public void setAncestorPath(String value)
    {
        setAttributeInternal(ANCESTORPATH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsSeeded.
     * @return the IsSeeded
     */
    public String getIsSeeded()
    {
        return (String)getAttributeInternal(ISSEEDED);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IsSeeded.
     * @param value value to set the  IsSeeded
     */
    public void setIsSeeded(String value)
    {
        setAttributeInternal(ISSEEDED, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SubGsCount.
     * @return the SubGsCount
     */
    public Number getSubGsCount()
    {
        return (Number)getAttributeInternal(SUBGSCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SubGsCount.
     * @param value value to set the  SubGsCount
     */
    public void setSubGsCount(Number value)
    {
        setAttributeInternal(SUBGSCOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute GsMemberCount.
     * @return the GsMemberCount
     */
    public Number getGsMemberCount()
    {
        return (Number)getAttributeInternal(GSMEMBERCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute GsMemberCount.
     * @param value value to set the  GsMemberCount
     */
    public void setGsMemberCount(Number value)
    {
        setAttributeInternal(GSMEMBERCOUNT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute EnterpriseId.
     * @return the EnterpriseId
     */
    public Number getEnterpriseId()
    {
        return (Number)getAttributeInternal(ENTERPRISEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute EnterpriseId.
     * @param value value to set the  EnterpriseId
     */
    public void setEnterpriseId(Number value)
    {
        setAttributeInternal(ENTERPRISEID, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link WcSpaceUsrDetailView.
     */
    public RowIterator getWcSpaceUsrDetailView()
    {
        return (RowIterator)getAttributeInternal(WCSPACEUSRDETAILVIEW);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ApplicationIdWcSpaceHeaderView.
     */
    public RowIterator getApplicationIdWcSpaceHeaderView()
    {
        return (RowIterator)getAttributeInternal(APPLICATIONIDWCSPACEHEADERVIEW);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception
    {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count()))
        {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception
    {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count()))
        {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    public SpaceHeader toBean()
    {
        SpaceHeader result = new SpaceHeader();

        result.setApplicationId(getApplicationId());
        result.setSpaceGuid(getSpaceGuid());
        result.setSpaceId(getSpaceId());
        result.setDisplayName(getDisplayName());
        result.setDescription(getDescription());
        result.setSpacePublic(getSpacePublic());
        result.setSpacesUser(getSpacesUser());
        result.setDiscoverable(getDiscoverable());
        result.setSpaceOffline(getSpaceOffline());
        result.setClosed(getClosed());
        result.setSelfSubEnabled(getSelfSubEnabled());
        result.setRssEnabled(getRssEnabled());
        result.setSpacesType(getSpacesType());
        result.setVersion(getVersion());
        result.setIcon(getIcon());
        result.setLogo(getLogo());
        result.setKeywords(getKeywords());
        result.setCreatedBy(getCreatedBy());
        result.setCreateDate(getCreateDate());
        result.setUpdatedBy(getUpdatedBy());
        result.setLastUpdateDate(getLastUpdateDate());
        result.setParentGuid(getParentGuid());
        result.setSecurityParentGuid(getSecurityParentGuid());
        result.setAncestorPath(getAncestorPath());
        result.setIsSeeded(getIsSeeded());
        result.setSubGsCount(getSubGsCount());
        result.setMemberCount(getGsMemberCount());
        result.setEnterpriseId(getEnterpriseId());

        return result;
    }
}
