package au.com.leighton.portal.peoplefinder.model;

import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 30 10:48:31 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WcSpaceUsrDetailViewRowImpl extends ViewRowImpl
{
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum
    {
        ApplicationId
        {
            public Object get(WcSpaceUsrDetailViewRowImpl obj)
            {
                return obj.getApplicationId();
            }

            public void put(WcSpaceUsrDetailViewRowImpl obj, Object value)
            {
                obj.setApplicationId((String)value);
            }
        },
        UserGuid
        {
            public Object get(WcSpaceUsrDetailViewRowImpl obj)
            {
                return obj.getUserGuid();
            }

            public void put(WcSpaceUsrDetailViewRowImpl obj, Object value)
            {
                obj.setUserGuid((String)value);
            }
        },
        SpaceId
        {
            public Object get(WcSpaceUsrDetailViewRowImpl obj)
            {
                return obj.getSpaceId();
            }

            public void put(WcSpaceUsrDetailViewRowImpl obj, Object value)
            {
                obj.setSpaceId((String)value);
            }
        },
        UserId
        {
            public Object get(WcSpaceUsrDetailViewRowImpl obj)
            {
                return obj.getUserId();
            }

            public void put(WcSpaceUsrDetailViewRowImpl obj, Object value)
            {
                obj.setUserId((String)value);
            }
        },
        IsGroup
        {
            public Object get(WcSpaceUsrDetailViewRowImpl obj)
            {
                return obj.getIsGroup();
            }

            public void put(WcSpaceUsrDetailViewRowImpl obj, Object value)
            {
                obj.setIsGroup((String)value);
            }
        },
        SpaceGuid
        {
            public Object get(WcSpaceUsrDetailViewRowImpl obj)
            {
                return obj.getSpaceGuid();
            }

            public void put(WcSpaceUsrDetailViewRowImpl obj, Object value)
            {
                obj.setSpaceGuid((String)value);
            }
        },
        SpaceRole
        {
            public Object get(WcSpaceUsrDetailViewRowImpl obj)
            {
                return obj.getSpaceRole();
            }

            public void put(WcSpaceUsrDetailViewRowImpl obj, Object value)
            {
                obj.setSpaceRole((String)value);
            }
        },
        PermissionAction
        {
            public Object get(WcSpaceUsrDetailViewRowImpl obj)
            {
                return obj.getPermissionAction();
            }

            public void put(WcSpaceUsrDetailViewRowImpl obj, Object value)
            {
                obj.setPermissionAction((String)value);
            }
        },
        Version
        {
            public Object get(WcSpaceUsrDetailViewRowImpl obj)
            {
                return obj.getVersion();
            }

            public void put(WcSpaceUsrDetailViewRowImpl obj, Object value)
            {
                obj.setVersion((Number)value);
            }
        },
        CreatedBy
        {
            public Object get(WcSpaceUsrDetailViewRowImpl obj)
            {
                return obj.getCreatedBy();
            }

            public void put(WcSpaceUsrDetailViewRowImpl obj, Object value)
            {
                obj.setCreatedBy((String)value);
            }
        },
        CreateDate
        {
            public Object get(WcSpaceUsrDetailViewRowImpl obj)
            {
                return obj.getCreateDate();
            }

            public void put(WcSpaceUsrDetailViewRowImpl obj, Object value)
            {
                obj.setCreateDate((Timestamp)value);
            }
        },
        UpdatedBy
        {
            public Object get(WcSpaceUsrDetailViewRowImpl obj)
            {
                return obj.getUpdatedBy();
            }

            public void put(WcSpaceUsrDetailViewRowImpl obj, Object value)
            {
                obj.setUpdatedBy((String)value);
            }
        },
        LastUpdateDate
        {
            public Object get(WcSpaceUsrDetailViewRowImpl obj)
            {
                return obj.getLastUpdateDate();
            }

            public void put(WcSpaceUsrDetailViewRowImpl obj, Object value)
            {
                obj.setLastUpdateDate((Timestamp)value);
            }
        },
        GroupSpaceType
        {
            public Object get(WcSpaceUsrDetailViewRowImpl obj)
            {
                return obj.getGroupSpaceType();
            }

            public void put(WcSpaceUsrDetailViewRowImpl obj, Object value)
            {
                obj.setGroupSpaceType((String)value);
            }
        },
        PermissionName
        {
            public Object get(WcSpaceUsrDetailViewRowImpl obj)
            {
                return obj.getPermissionName();
            }

            public void put(WcSpaceUsrDetailViewRowImpl obj, Object value)
            {
                obj.setPermissionName((String)value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(WcSpaceUsrDetailViewRowImpl object);

        public abstract void put(WcSpaceUsrDetailViewRowImpl object,
                                 Object value);

        public int index()
        {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex()
        {
            return firstIndex;
        }

        public static int count()
        {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues()
        {
            if (vals == null)
            {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int APPLICATIONID =
        AttributesEnum.ApplicationId.index();
    public static final int USERGUID = AttributesEnum.UserGuid.index();
    public static final int SPACEID = AttributesEnum.SpaceId.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int ISGROUP = AttributesEnum.IsGroup.index();
    public static final int SPACEGUID = AttributesEnum.SpaceGuid.index();
    public static final int SPACEROLE = AttributesEnum.SpaceRole.index();
    public static final int PERMISSIONACTION =
        AttributesEnum.PermissionAction.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDATE = AttributesEnum.CreateDate.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int LASTUPDATEDATE =
        AttributesEnum.LastUpdateDate.index();
    public static final int GROUPSPACETYPE =
        AttributesEnum.GroupSpaceType.index();
    public static final int PERMISSIONNAME =
        AttributesEnum.PermissionName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public WcSpaceUsrDetailViewRowImpl()
    {
    }

    /**
     * Gets the attribute value for the calculated attribute ApplicationId.
     * @return the ApplicationId
     */
    public String getApplicationId()
    {
        return (String)getAttributeInternal(APPLICATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ApplicationId.
     * @param value value to set the  ApplicationId
     */
    public void setApplicationId(String value)
    {
        setAttributeInternal(APPLICATIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UserGuid.
     * @return the UserGuid
     */
    public String getUserGuid()
    {
        return (String)getAttributeInternal(USERGUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UserGuid.
     * @param value value to set the  UserGuid
     */
    public void setUserGuid(String value)
    {
        setAttributeInternal(USERGUID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SpaceId.
     * @return the SpaceId
     */
    public String getSpaceId()
    {
        return (String)getAttributeInternal(SPACEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SpaceId.
     * @param value value to set the  SpaceId
     */
    public void setSpaceId(String value)
    {
        setAttributeInternal(SPACEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UserId.
     * @return the UserId
     */
    public String getUserId()
    {
        return (String)getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UserId.
     * @param value value to set the  UserId
     */
    public void setUserId(String value)
    {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IsGroup.
     * @return the IsGroup
     */
    public String getIsGroup()
    {
        return (String)getAttributeInternal(ISGROUP);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IsGroup.
     * @param value value to set the  IsGroup
     */
    public void setIsGroup(String value)
    {
        setAttributeInternal(ISGROUP, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SpaceGuid.
     * @return the SpaceGuid
     */
    public String getSpaceGuid()
    {
        return (String)getAttributeInternal(SPACEGUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SpaceGuid.
     * @param value value to set the  SpaceGuid
     */
    public void setSpaceGuid(String value)
    {
        setAttributeInternal(SPACEGUID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SpaceRole.
     * @return the SpaceRole
     */
    public String getSpaceRole()
    {
        return (String)getAttributeInternal(SPACEROLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SpaceRole.
     * @param value value to set the  SpaceRole
     */
    public void setSpaceRole(String value)
    {
        setAttributeInternal(SPACEROLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PermissionAction.
     * @return the PermissionAction
     */
    public String getPermissionAction()
    {
        return (String)getAttributeInternal(PERMISSIONACTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PermissionAction.
     * @param value value to set the  PermissionAction
     */
    public void setPermissionAction(String value)
    {
        setAttributeInternal(PERMISSIONACTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Version.
     * @return the Version
     */
    public Number getVersion()
    {
        return (Number)getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Version.
     * @param value value to set the  Version
     */
    public void setVersion(Number value)
    {
        setAttributeInternal(VERSION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy()
    {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy.
     * @param value value to set the  CreatedBy
     */
    public void setCreatedBy(String value)
    {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreateDate.
     * @return the CreateDate
     */
    public Timestamp getCreateDate()
    {
        return (Timestamp)getAttributeInternal(CREATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreateDate.
     * @param value value to set the  CreateDate
     */
    public void setCreateDate(Timestamp value)
    {
        setAttributeInternal(CREATEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UpdatedBy.
     * @return the UpdatedBy
     */
    public String getUpdatedBy()
    {
        return (String)getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UpdatedBy.
     * @param value value to set the  UpdatedBy
     */
    public void setUpdatedBy(String value)
    {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Timestamp getLastUpdateDate()
    {
        return (Timestamp)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate.
     * @param value value to set the  LastUpdateDate
     */
    public void setLastUpdateDate(Timestamp value)
    {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute GroupSpaceType.
     * @return the GroupSpaceType
     */
    public String getGroupSpaceType()
    {
        return (String)getAttributeInternal(GROUPSPACETYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute GroupSpaceType.
     * @param value value to set the  GroupSpaceType
     */
    public void setGroupSpaceType(String value)
    {
        setAttributeInternal(GROUPSPACETYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PermissionName.
     * @return the PermissionName
     */
    public String getPermissionName()
    {
        return (String)getAttributeInternal(PERMISSIONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PermissionName.
     * @param value value to set the  PermissionName
     */
    public void setPermissionName(String value)
    {
        setAttributeInternal(PERMISSIONNAME, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception
    {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count()))
        {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception
    {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count()))
        {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    public Space toBean()
    {
        Space result = new Space();

        result.setApplicationId(getApplicationId());
        result.setSpaceGuid(getSpaceGuid());
        result.setUserGuid(getUserGuid());
        result.setSpaceId(getSpaceId());
        result.setUserId(getUserId());
        result.setIsGroup(getIsGroup());
        result.setSpaceRole(getSpaceRole());
        result.setPermissionAction(getPermissionAction());
        result.setVersion(getVersion());
        result.setCreatedBy(getCreatedBy());
        result.setCreateDate(getCreateDate());
        result.setUpdatedBy(getUpdatedBy());
        result.setLastUpdatedDate(getLastUpdateDate());
        result.setGroupSpaceType(getGroupSpaceType());
        result.setPermissionName(getPermissionName());

        return result;
    }
}
