package au.com.leighton.portal.peoplefinder.model;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 30 10:48:32 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WcSpaceUsrDetailViewDefImpl extends ViewDefImpl
{
    public WcSpaceUsrDetailViewDefImpl(String name)
    {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public WcSpaceUsrDetailViewDefImpl()
    {
    }
}
