package au.com.leighton.portal.peoplefinder.model;

import java.util.ArrayList;
import java.util.List;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 30 10:48:32 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WcSpaceUsrDetailViewImpl extends ViewObjectImpl
{
    /**
     * This is the default constructor (do not remove).
     */
    public WcSpaceUsrDetailViewImpl()
    {
    }

    /**
     * Returns the bind variable value for username.
     * @return bind variable value for username
     */
    public String getusername()
    {
        return (String)getNamedWhereClauseParam("username");
    }

    /**
     * Sets <code>value</code> for bind variable username.
     * @param value value to bind as username
     */
    public void setusername(String value)
    {
        setNamedWhereClauseParam("username", value);
    }

    public List<Space> getSpacesForUser(String username)
    {
        List<Space> result = new ArrayList<Space>();
        setusername(username);

        this.executeQuery();

        WcSpaceUsrDetailViewRowImpl currentRow = null;

        while ((currentRow = (WcSpaceUsrDetailViewRowImpl)next()) != null)
        {
            Space space = currentRow.toBean();

            result.add(space);
        }

        return result;
    }
}
