package au.com.leighton.portal.peoplefinder.model.peopledetail;

import au.com.leighton.portal.peoplefinder.model.peopledetail.generated.ObjectFactory;
import au.com.leighton.portal.peoplefinder.model.peopledetail.generated.PhoGetPersonDetailOutput;

import java.math.BigDecimal;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebService(wsdlLocation="http://lclxsoa11gdev.lc.local:7001/soa-infra/services/default/PhoGetPersonDetail/phogetpersondetail_client_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/Portal/PhoGetPersonDetail/PhoGetPersonDetail",
  name="PhoGetPersonDetail")
@XmlSeeAlso(
  { ObjectFactory.class })
public interface PhoGetPersonDetail
{
  @WebMethod(action="process")
  @Action(input="process", output="http://xmlns.oracle.com/Portal/PhoGetPersonDetail/PhoGetPersonDetail/PhoGetPersonDetail/processResponse")
  @ResponseWrapper(localName="processResponse", targetNamespace="http://xmlns.oracle.com/Portal/PhoGetPersonDetail/PhoGetPersonDetail",
    className="au.com.leighton.portal.peoplefinder.model.peopledetail.generated.PhoGetPersonDetailCollection")
  @RequestWrapper(localName="process", targetNamespace="http://xmlns.oracle.com/Portal/PhoGetPersonDetail/PhoGetPersonDetail",
    className="au.com.leighton.portal.peoplefinder.model.peopledetail.generated.Process")
  public void process(@WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoGetPersonDetail/PhoGetPersonDetail",
      name="i_person_id")
    BigDecimal iPersonId, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoGetPersonDetail/PhoGetPersonDetail",
      name="i_username")
    String iUsername, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoGetPersonDetail/PhoGetPersonDetail",
      name="RESULT", mode=Mode.OUT)
    Holder<String> result, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoGetPersonDetail/PhoGetPersonDetail",
      name="PhoPerson", mode=Mode.OUT)
    Holder<List<PhoGetPersonDetailOutput>> phoPerson);
}
