package au.com.leighton.model.view;

import au.com.leighton.model.util.EnvironmentUtil;
import au.com.leighton.model.util.LogUtility;
import au.com.leighton.model.view.common.EAapplicationListVO;

import oracle.jbo.ViewObject;
import oracle.jbo.server.DBTransaction;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 03 18:15:52 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EAapplicationListVOImpl extends ViewObjectImpl implements EAapplicationListVO {
    /**
     * This is the default constructor (do not remove).
     */
    public EAapplicationListVOImpl() {

    }

    /**
     * Returns the bind variable value for userlogin.
     * @return bind variable value for userlogin
     */
    public String getuserlogin() {
        return (String)getNamedWhereClauseParam("userlogin");
    }

    /**
     * Sets <code>value</code> for bind variable userlogin.
     * @param value value to bind as userlogin
     */
    public void setuserlogin(String value) {
        setNamedWhereClauseParam("userlogin", value);
    }

    /**
     * getenterpiseList: Display the List according to username from table   EA_APPLICATION .

     * @param username the username id
     * @throws Exception
     */
    public void getenterpiseList(String username) {
        username = EnvironmentUtil.getUsername();
        try {
            DBTransaction bTransaction = getDBTransaction();
            ViewObject vo = bTransaction.findViewObject("EAapplicationListVO");
            vo.setNamedWhereClauseParam("userlogin", username);
            vo.executeQuery();
        } catch (Exception e) {
            String message = e.getMessage();
            LogUtility.logSevere(EnvironmentUtil.class, message, e);
        }
    }
}
