package au.com.leicon.ess.services;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebServiceClient(wsdlLocation="http://lclxsoar1u.lc.local:8001/soa-infra/services/default/ESSDetailsComposite/myessdetails_client_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/PortalApplication/ESSDetailsComposite/MyESSDetails",
  name="myessdetails_client_ep")
public class Myessdetails_client_ep
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("au.com.leicon.ess.services.Myessdetails_client_ep");
      URL baseUrl = Myessdetails_client_ep.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            Myessdetails_client_ep.class.getResource("http://lclxsoar1u.lc.local:8001/soa-infra/services/default/ESSDetailsComposite/myessdetails_client_ep?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://lclxsoar1u.lc.local:8001/soa-infra/services/default/ESSDetailsComposite/myessdetails_client_ep?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://lclxsoar1u.lc.local:8001/soa-infra/services/default/ESSDetailsComposite/myessdetails_client_ep?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://lclxsoar1u.lc.local:8001/soa-infra/services/default/ESSDetailsComposite/myessdetails_client_ep?WSDL",
          e);
    }
  }

  public Myessdetails_client_ep()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/PortalApplication/ESSDetailsComposite/MyESSDetails",
                    "myessdetails_client_ep"));
  }

  public Myessdetails_client_ep(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="MyESSDetails_pt")
  public MyESSDetails getMyESSDetails_pt()
  {
    return (MyESSDetails) super.getPort(new QName("http://xmlns.oracle.com/PortalApplication/ESSDetailsComposite/MyESSDetails",
                                                  "MyESSDetails_pt"),
                                        MyESSDetails.class);
  }

  @WebEndpoint(name="MyESSDetails_pt")
  public MyESSDetails getMyESSDetails_pt(WebServiceFeature... features)
  {
    return (MyESSDetails) super.getPort(new QName("http://xmlns.oracle.com/PortalApplication/ESSDetailsComposite/MyESSDetails",
                                                  "MyESSDetails_pt"),
                                        MyESSDetails.class, features);
  }
}
