package au.com.leicon.ess.services;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

public class MyESSDetails_ptClient
{
  @WebServiceRef
  private static Myessdetails_client_ep myessdetails_client_ep;

  public static void main(String [] args)
  {
    myessdetails_client_ep = new Myessdetails_client_ep();
    MyESSDetails myESSDetails = myessdetails_client_ep.getMyESSDetails_pt();
    // Add your code to call the desired methods.
  }
}
