package au.com.leighton.mytrainings.model.view.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 23 16:46:32 IST 2012
// ---------------------------------------------------------------------
public interface MyTrainingListCategoryVORow extends Row {

    void deleteCourse(Number curseId);
}
