package au.com.leighton.mytrainings.model.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 24 18:34:39 IST 2012
// ---------------------------------------------------------------------
public interface MyTrainingListCategoryVO extends ViewObject {
    void getTainingCategorybyList();
}
