package au.com.leighton.mytrainings.model.view.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 25 12:13:44 IST 2012
// ---------------------------------------------------------------------
public interface NonMandatoryTraining_VORow extends Row {
    void createCourse(Number curseId);
}
