package au.com.leighton.mytrainings.model.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 29 20:25:41 IST 2012
// ---------------------------------------------------------------------
public interface NonMandatoryTraining_VO extends ViewObject {
    void getNonMandatoryList();
}
