package au.com.leighton.model.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 03 18:16:29 IST 2012
// ---------------------------------------------------------------------
public interface EAapplicationListVO extends ViewObject {
    void getenterpiseList(String username);
}
