package au.com.leighton.model.view.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 05 11:15:50 IST 2012
// ---------------------------------------------------------------------
public interface EAapplicationEditVORow extends Row {
    void createSelectedRow();

}
