package au.com.leighton.portal.aggregatedtasklist.model.service.tasklistaggregator;


import au.com.leighton.portal.aggregatedtasklist.model.service.tasklistaggregator.types.TaskListAggregatorFault;

import javax.xml.ws.WebFault;

@WebFault(faultBean =
          "au.com.leighton.portal.aggregatedtasklist.model.service.tasklistaggregator.types.TaskListAggregatorFault",
          targetNamespace =
          "http://xmlns.leicon.com.au/Portal/TaskListAggregator/TaskListAggregator",
          name = "taskListAggregatorFault")
public class TaskListAggregatorFaultMessage extends Exception
{
    private TaskListAggregatorFault faultInfo;

    public TaskListAggregatorFaultMessage(String message,
                                          TaskListAggregatorFault faultInfo)
    {
        super(message);
        this.faultInfo = faultInfo;
    }

    public TaskListAggregatorFaultMessage(String message,
                                          TaskListAggregatorFault faultInfo,
                                          Throwable t)
    {
        super(message, t);
        this.faultInfo = faultInfo;
    }

    public TaskListAggregatorFault getFaultInfo()
    {
        return faultInfo;
    }

    public void setFaultInfo(TaskListAggregatorFault faultInfo)
    {
        this.faultInfo = faultInfo;
    }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)
