package au.com.leighton.portal.aggregatedtasklist.model.service.tasklistaggregator;


import au.com.leighton.portal.aggregatedtasklist.model.service.tasklistaggregator.types.GetTasksInput;
import au.com.leighton.portal.aggregatedtasklist.model.service.tasklistaggregator.types.GetTasksOutput;
import au.com.leighton.portal.aggregatedtasklist.model.service.tasklistaggregator.types.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebService(wsdlLocation =
            "http://lclxsoa11gdev.lc.local:7001/soa-infra/services/default/TaskListAggregator/tasklistaggregator_client_ep?WSDL",
            targetNamespace =
            "http://xmlns.leicon.com.au/Portal/TaskListAggregator/TaskListAggregator",
            name = "TaskListAggregator")
@XmlSeeAlso(
    { ObjectFactory.class })
public interface TaskListAggregator
{
    @WebMethod(action = "getTasks")
    @SOAPBinding(parameterStyle = ParameterStyle.BARE)
    @Action(input = "getTasks", fault =
            { @FaultAction(value =
                           "http://xmlns.leicon.com.au/Portal/TaskListAggregator/TaskListAggregator/TaskListAggregator/getTasks/Fault/fault",
                           className = TaskListAggregatorFaultMessage.class) },
        output =
            "http://xmlns.leicon.com.au/Portal/TaskListAggregator/TaskListAggregator/TaskListAggregator/getTasksResponse")
    @WebResult(targetNamespace =
               "http://xmlns.leicon.com.au/Portal/TaskListAggregator/TaskListAggregator",
               partName = "payload", name = "getTasksOutput")
    public GetTasksOutput getTasks(@WebParam(targetNamespace =
                                             "http://xmlns.leicon.com.au/Portal/TaskListAggregator/TaskListAggregator",
                                             partName = "payload",
                                             name = "getTasksInput")
        GetTasksInput payload) throws TaskListAggregatorFaultMessage;
}
