package au.com.leighton.myconnections.model.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 18 11:09:08 IST 2012
// ---------------------------------------------------------------------
public interface ConnectionPeopleListVO extends ViewObject {
    void getMyConnectionLists();
}
