package au.com.leighton.model.view.client;

import au.com.leighton.model.view.common.EAapplicationEditVORow;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 05 11:15:50 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EAapplicationEditVORowClient extends RowImpl implements EAapplicationEditVORow {
    /**
     * This is the default constructor (do not remove).
     */
    public EAapplicationEditVORowClient() {
    }


    public void createSelectedRow() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"createSelectedRow",null,null);
        return;
    }

    public void checkSelectedBox() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"checkSelectedBox",null,null);
        return;
    }
}
