package au.com.leighton.model.view.client;

import au.com.leighton.model.view.common.EAapplicationListVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 03 18:16:29 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EAapplicationListVOClient extends ViewUsageImpl implements EAapplicationListVO {
    /**
     * This is the default constructor (do not remove).
     */
    public EAapplicationListVOClient() {
    }

    public void getenterpiseList(String username) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getenterpiseList",new String [] {"java.lang.String"},new Object[] {username});
        return;
    }
}
