package au.com.leighton.portal.innovation.model.common;

import au.com.leighton.portal.innovation.model.FilterBean;
import au.com.leighton.portal.innovation.model.IdeaBean;
import au.com.leighton.portal.innovation.model.InnovationBean;

import java.util.List;

import javax.faces.model.SelectItem;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 17 13:18:15 EST 2011
// ---------------------------------------------------------------------
public interface AppModuleModel extends ApplicationModule
{
    void updateInnovation(InnovationBean innovationBean, String emailAddress);

    void storeNewIdea(IdeaBean newIdeaBean, String currentUsername,
                      String emailAddress);

    void storeFilter(FilterBean filterBean, boolean storeIdeaComponents,
                     boolean storeInnovationComponents);

    void processNotAdopt(Number submittedInnovationId, String newStatus,
                         String comment, String emailAddress);

    void processAdopt(IdeaBean ideaBean, InnovationBean innovationBean,
                      String emailAddress);

    boolean isUserInRoleForDivision(String username, String divisionName);

    List<InnovationBean> getInnovationList(String[] categories,
                                           String[] divisions,
                                           String[] statuses, Date fromDate,
                                           Date toDate,
                                           String ideaSubmittedByUsername);

    List<IdeaBean> getIdeaList(String[] divisions, String[] statuses,
                               Date fromDate, Date toDate);

    FilterBean getFilter(String username);

    List<SelectItem> getDropDownValuesInnovationStatusFilter();

    List<SelectItem> getDropDownValuesInnovationStatus();

    List<SelectItem> getDropDownValuesInnovationCategoryFilter();

    List<SelectItem> getDropDownValuesIdeaStatusFilter();

    List<SelectItem> getDropDownValuesDivisionFilter();

    List<SelectItem> getDropDownValuesDivision();

    List<SelectItem> getDropDownValuesCategory();

    List<SelectItem> getDropDownValuesBusinessOptimisation();

    List<SelectItem> getDropDownValuesBenefit();

    List<String> getDivisionsForUser(String username);
}
