package au.com.leighton.myconnections.model.view.client;

import au.com.leighton.myconnections.model.view.common.ConnectionPeopleListVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 18 11:09:08 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ConnectionPeopleListVOClient extends ViewUsageImpl implements ConnectionPeopleListVO {
    /**
     * This is the default constructor (do not remove).
     */
    public ConnectionPeopleListVOClient() {
    }

    public void getMyConnectionLists() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getMyConnectionLists",null,null);
        return;
    }
}
