package au.com.leighton.portal.profile.model.common;


import au.com.leighton.portal.profile.IExperience;
import au.com.leighton.portal.profile.IExperienceItem;
import au.com.leighton.portal.profile.IWorkHistory;
import au.com.leighton.portal.profile.IWorkHistoryItem;
import au.com.leighton.portal.profile.ProfileResponse;

import java.util.List;

import oracle.jbo.ApplicationModule;
import oracle.jbo.domain.Date;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 01 09:22:00 EST 2011
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule
{
    ProfileResponse updateWorkHistoryItem(IWorkHistoryItem original,
                                          String role, String company,
                                          String location, Date fromDate,
                                          Date toDate, String jobDescription);

    ProfileResponse updateExperienceItem(IExperienceItem original,
                                         String title,
                                         String experienceDescription);

    ProfileResponse getWorkHistory(String username);

    ProfileResponse getExperience(String username);

    List<IWorkHistoryItem> getAllWorkHistoryItems();

    List<IExperienceItem> getAllExperienceItems();

    ProfileResponse deleteWorkHistoryItem(IWorkHistory workHistory,
                                          IWorkHistoryItem workHistoryItem);

    ProfileResponse deleteExperienceItem(IExperience experience,
                                         IExperienceItem experienceItem);

    ProfileResponse createWorkHistoryItem(IWorkHistory workHistory,
                                          String role, String company,
                                          String location, Date fromDate,
                                          Date toDate, String jobDescription);

    ProfileResponse createExperienceItem(IExperience experience, String title,
                                         String experienceDescription);
}
