package au.com.leighton.myspaces.model.view;

import au.com.leighton.myspaces.model.EnvironmentUtil;
import au.com.leighton.myspaces.model.LogUtility;
import au.com.leighton.myspaces.model.Utility;

import java.util.GregorianCalendar;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 14 16:54:35 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MySpacesListVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Description {
            public Object get(MySpacesListVORowImpl obj) {
                return obj.getDescription();
            }

            public void put(MySpacesListVORowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        }
        ,
        ApplicationId {
            public Object get(MySpacesListVORowImpl obj) {
                return obj.getApplicationId();
            }

            public void put(MySpacesListVORowImpl obj, Object value) {
                obj.setApplicationId((String)value);
            }
        }
        ,
        SpaceGuid {
            public Object get(MySpacesListVORowImpl obj) {
                return obj.getSpaceGuid();
            }

            public void put(MySpacesListVORowImpl obj, Object value) {
                obj.setSpaceGuid((String)value);
            }
        }
        ,
        DisplayName {
            public Object get(MySpacesListVORowImpl obj) {
                return obj.getDisplayName();
            }

            public void put(MySpacesListVORowImpl obj, Object value) {
                obj.setDisplayName((String)value);
            }
        }
        ,
        UpdatedBy {
            public Object get(MySpacesListVORowImpl obj) {
                return obj.getUpdatedBy();
            }

            public void put(MySpacesListVORowImpl obj, Object value) {
                obj.setUpdatedBy((String)value);
            }
        }
        ,
        UserId {
            public Object get(MySpacesListVORowImpl obj) {
                return obj.getUserId();
            }

            public void put(MySpacesListVORowImpl obj, Object value) {
                obj.setUserId((String)value);
            }
        }
        ,
        ApplicationId1 {
            public Object get(MySpacesListVORowImpl obj) {
                return obj.getApplicationId1();
            }

            public void put(MySpacesListVORowImpl obj, Object value) {
                obj.setApplicationId1((String)value);
            }
        }
        ,
        UserGuid {
            public Object get(MySpacesListVORowImpl obj) {
                return obj.getUserGuid();
            }

            public void put(MySpacesListVORowImpl obj, Object value) {
                obj.setUserGuid((String)value);
            }
        }
        ,
        SpaceGuid1 {
            public Object get(MySpacesListVORowImpl obj) {
                return obj.getSpaceGuid1();
            }

            public void put(MySpacesListVORowImpl obj, Object value) {
                obj.setSpaceGuid1((String)value);
            }
        }
        ,
        SpaceId {
            public Object get(MySpacesListVORowImpl obj) {
                return obj.getSpaceId();
            }

            public void put(MySpacesListVORowImpl obj, Object value) {
                obj.setSpaceId((String)value);
            }
        }
        ,
        memberCount {
            public Object get(MySpacesListVORowImpl obj) {
                return obj.getmemberCount();
            }

            public void put(MySpacesListVORowImpl obj, Object value) {
                obj.setmemberCount((String)value);
            }
        }
        ,
        SpaceLastUpdate {
            public Object get(MySpacesListVORowImpl obj) {
                return obj.getSpaceLastUpdate();
            }

            public void put(MySpacesListVORowImpl obj, Object value) {
                obj.setSpaceLastUpdate((String)value);
            }
        }
        ,
        Closed {
            public Object get(MySpacesListVORowImpl obj) {
                return obj.getClosed();
            }

            public void put(MySpacesListVORowImpl obj, Object value) {
                obj.setClosed((String)value);
            }
        }
        ,
        Logo {
            public Object get(MySpacesListVORowImpl obj) {
                return obj.getLogo();
            }

            public void put(MySpacesListVORowImpl obj, Object value) {
                obj.setLogo((String)value);
            }
        }
        ,
        LastUpdateDate1 {
            public Object get(MySpacesListVORowImpl obj) {
                return obj.getLastUpdateDate1();
            }

            public void put(MySpacesListVORowImpl obj, Object value) {
                obj.setLastUpdateDate1((Timestamp)value);
            }
        }
        ,
        MySpacecountVO1 {
            public Object get(MySpacesListVORowImpl obj) {
                return obj.getMySpacecountVO1();
            }

            public void put(MySpacesListVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MySpacesListVORowImpl object);

        public abstract void put(MySpacesListVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int APPLICATIONID = AttributesEnum.ApplicationId.index();
    public static final int SPACEGUID = AttributesEnum.SpaceGuid.index();
    public static final int DISPLAYNAME = AttributesEnum.DisplayName.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int APPLICATIONID1 = AttributesEnum.ApplicationId1.index();
    public static final int USERGUID = AttributesEnum.UserGuid.index();
    public static final int SPACEGUID1 = AttributesEnum.SpaceGuid1.index();
    public static final int SPACEID = AttributesEnum.SpaceId.index();
    public static final int MEMBERCOUNT = AttributesEnum.memberCount.index();
    public static final int SPACELASTUPDATE = AttributesEnum.SpaceLastUpdate.index();
    public static final int CLOSED = AttributesEnum.Closed.index();
    public static final int LOGO = AttributesEnum.Logo.index();
    public static final int LASTUPDATEDATE1 = AttributesEnum.LastUpdateDate1.index();
    public static final int MYSPACECOUNTVO1 = AttributesEnum.MySpacecountVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MySpacesListVORowImpl() {
    }

    /**
     * Gets WcSpaceHeader entity object.
     * @return the WcSpaceHeader
     */
    public EntityImpl getWcSpaceHeader() {
        return (EntityImpl)getEntity(0);
    }

    /**
     * Gets WcSpaceUsrDetail entity object.
     * @return the WcSpaceUsrDetail
     */
    public EntityImpl getWcSpaceUsrDetail() {
        return (EntityImpl)getEntity(1);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String)getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for APPLICATION_ID using the alias name ApplicationId.
     * @return the APPLICATION_ID
     */
    public String getApplicationId() {
        return (String)getAttributeInternal(APPLICATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for APPLICATION_ID using the alias name ApplicationId.
     * @param value value to set the APPLICATION_ID
     */
    public void setApplicationId(String value) {
        setAttributeInternal(APPLICATIONID, value);
    }

    /**
     * Gets the attribute value for SPACE_GUID using the alias name SpaceGuid.
     * @return the SPACE_GUID
     */
    public String getSpaceGuid() {
        return (String)getAttributeInternal(SPACEGUID);
    }

    /**
     * Sets <code>value</code> as attribute value for SPACE_GUID using the alias name SpaceGuid.
     * @param value value to set the SPACE_GUID
     */
    public void setSpaceGuid(String value) {
        setAttributeInternal(SPACEGUID, value);
    }

    /**
     * Gets the attribute value for DISPLAY_NAME using the alias name DisplayName.
     * @return the DISPLAY_NAME
     */
    public String getDisplayName() {
        return (String)getAttributeInternal(DISPLAYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for DISPLAY_NAME using the alias name DisplayName.
     * @param value value to set the DISPLAY_NAME
     */
    public void setDisplayName(String value) {
        setAttributeInternal(DISPLAYNAME, value);
    }


    /**
     * Gets the attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @return the UPDATED_BY
     */
    public String getUpdatedBy() {
        return (String)getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for UPDATED_BY using the alias name UpdatedBy.
     * @param value value to set the UPDATED_BY
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for USER_ID using the alias name UserId.
     * @return the USER_ID
     */
    public String getUserId() {
        return (String)getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_ID using the alias name UserId.
     * @param value value to set the USER_ID
     */
    public void setUserId(String value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for APPLICATION_ID using the alias name ApplicationId1.
     * @return the APPLICATION_ID
     */
    public String getApplicationId1() {
        return (String)getAttributeInternal(APPLICATIONID1);
    }

    /**
     * Sets <code>value</code> as attribute value for APPLICATION_ID using the alias name ApplicationId1.
     * @param value value to set the APPLICATION_ID
     */
    public void setApplicationId1(String value) {
        setAttributeInternal(APPLICATIONID1, value);
    }

    /**
     * Gets the attribute value for USER_GUID using the alias name UserGuid.
     * @return the USER_GUID
     */
    public String getUserGuid() {
        return (String)getAttributeInternal(USERGUID);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_GUID using the alias name UserGuid.
     * @param value value to set the USER_GUID
     */
    public void setUserGuid(String value) {
        setAttributeInternal(USERGUID, value);
    }

    /**
     * Gets the attribute value for SPACE_GUID using the alias name SpaceGuid1.
     * @return the SPACE_GUID
     */
    public String getSpaceGuid1() {
        return (String)getAttributeInternal(SPACEGUID1);
    }

    /**
     * Sets <code>value</code> as attribute value for SPACE_GUID using the alias name SpaceGuid1.
     * @param value value to set the SPACE_GUID
     */
    public void setSpaceGuid1(String value) {
        setAttributeInternal(SPACEGUID1, value);
    }

    /**
     * Gets the attribute value for SPACE_ID using the alias name SpaceId.
     * @return the SPACE_ID
     */
    public String getSpaceId() {
        return (String)getAttributeInternal(SPACEID);
    }

    /**
     * Sets <code>value</code> as attribute value for SPACE_ID using the alias name SpaceId.
     * @param value value to set the SPACE_ID
     */
    public void setSpaceId(String value) {
        setAttributeInternal(SPACEID, value);
    }


    /**
     * Gets the attribute value for MEMBERCOUNT using the alias name memberCount.
     * @return the MEMBERCOUNT
     */
    public String getmemberCount() {
        String membercount = countMembers(getSpaceId());
        return membercount;
    }

    /**
     * Sets <code>value</code> as attribute value for MEMBERCOUNT using the alias name memberCount.
     * @param value value to set the MEMBERCOUNT
     */
    public void setmemberCount(String value) {
        setAttributeInternal(MEMBERCOUNT, value);

    }


    /**
     * Gets the attribute value for the calculated attribute SpaceLastUpdate.
     * @return the SpaceLastUpdate
     */
    public String getSpaceLastUpdate() {
        String newlastUpdate = getLastActivityText(getLastUpdateDate1());
        return newlastUpdate;
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SpaceLastUpdate.
     * @param value value to set the  SpaceLastUpdate
     */
    public void setSpaceLastUpdate(String value) {
        setAttributeInternal(SPACELASTUPDATE, value);
    }

    /**
     * Gets the attribute value for CLOSED using the alias name Closed.
     * @return the CLOSED
     */
    public String getClosed() {
        return (String)getAttributeInternal(CLOSED);
    }

    /**
     * Sets <code>value</code> as attribute value for CLOSED using the alias name Closed.
     * @param value value to set the CLOSED
     */
    public void setClosed(String value) {
        setAttributeInternal(CLOSED, value);
    }

    /**
     * Gets the attribute value for LOGO using the alias name Logo.
     * @return the LOGO
     */
    public String getLogo() {


        String imagePrefix="//webcenter/webcenter-spaces-resources";
        String logoPath = (String)getAttributeInternal(LOGO);
        if (logoPath.indexOf("{SHARED_RES_BASE_LOCATION}") >=0)
        {
            logoPath= logoPath.substring(26); //line 4  
            imagePrefix= Utility.getSpacesImagePrefix();
        }
        StringBuffer strUrl = new StringBuffer(imagePrefix);
        strUrl.append(logoPath);
        String finalPath = "";
        if (logoPath == null || logoPath.equals("")) {
            finalPath = "/nophoto.png";
        } else {
            finalPath = strUrl.toString();
        }
        return finalPath;
    }

    /**
     * Sets <code>value</code> as attribute value for LOGO using the alias name Logo.
     * @param value value to set the LOGO
     */
    public void setLogo(String value) {
        setAttributeInternal(LOGO, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate1.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate1() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE1);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate1.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate1(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE1, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MySpacecountVO1.
     */
    public RowSet getMySpacecountVO1() {
        return (RowSet)getAttributeInternal(MYSPACECOUNTVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    public String countMembers(String mySpaceId) {
        StringBuilder sb = new StringBuilder();
        try {
            RowSet rowsList = getMySpacecountVO1();
            Row[] row = rowsList.getFilteredRows("SpaceId", mySpaceId);
            int rowcounts = row.length;

            if (rowcounts > 0) {
                sb.append(String.valueOf(rowcounts));
                if (rowcounts == 1)
                    sb.append(" Member");
                else
                    sb.append(" Members");

                return sb.toString();
            } else
                return "No Members";
        } catch (Exception e) {
            String message = e.getMessage();
            LogUtility.logSevere(EnvironmentUtil.class, message, e);
            return "No Members";
        }

    }

    public String getLastActivityText(Timestamp lastupdate) {
        StringBuffer result = new StringBuffer();

        if (lastupdate != null) {
            GregorianCalendar now = new GregorianCalendar();
            GregorianCalendar update = new GregorianCalendar();
            update.setTime(lastupdate.getValue());

            long n = now.getTimeInMillis();
            long u = update.getTimeInMillis();

            long milliseconds = n - u;

            int days = (int)(milliseconds / (1000L * 60L * 60L * 24L));

            result.append("Last Activity ");

            if (days == 0) {
                result.append("Today");
            } else {
                result.append(days);
                result.append(" day");

                if (days > 1) {
                    result.append("s");
                }

                result.append(" ago");
            }
        }

        return result.toString();
    }
}
