package au.com.leighton.myconnections.model.view;

import au.com.leighton.myconnections.model.EnvironmentUtil;

import au.com.leighton.myconnections.model.view.common.ConnectionPeopleListVO;

import oracle.jbo.ViewObject;
import oracle.jbo.server.DBTransaction;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 17 16:45:51 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ConnectionPeopleListVOImpl extends ViewObjectImpl implements ConnectionPeopleListVO {
    /**
     * This is the default constructor (do not remove).
     */
    public ConnectionPeopleListVOImpl() {
    }

    /**
     * Returns the bind variable value for userName.
     * @return bind variable value for userName
     */
    public String getuserName() {
        return (String)getNamedWhereClauseParam("userName");
    }

    /**
     * Sets <code>value</code> for bind variable userName.
     * @param value value to bind as userName
     */
    public void setuserName(String value) {
        System.out.println("User name "+value);
        setNamedWhereClauseParam("userName", value);
    }
    
    public void getMyConnectionLists() {
        String username="";
        username = EnvironmentUtil.getUsername();
        try {
            DBTransaction bTransaction = getDBTransaction();
            ViewObject vo = bTransaction.findViewObject("ConnectionPeopleListVO1");
            vo.setNamedWhereClauseParam("userName", username);
            vo.executeQuery();
        } catch (Exception e) {
            String message = e.getMessage();
            //LogUtility.logSevere(EnvironmentUtil.class, message, e);
        }
    }
  
}
