package au.com.leighton.myspaces.model.view.client;

import au.com.leighton.myspaces.model.view.common.MySpacesListVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 14 17:00:28 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MySpacesListVOClient extends ViewUsageImpl implements MySpacesListVO {
    /**
     * This is the default constructor (do not remove).
     */
    public MySpacesListVOClient() {
    }

    public void getMySpaceLists(String username) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getMySpaceLists",new String [] {"java.lang.String"},new Object[] {username});
        return;
    }
}
