package au.com.leighton.mytrainings.model.view;

import au.com.leighton.mytrainings.model.util.EnvironmentUtil;

import au.com.leighton.mytrainings.model.util.LogUtility;
import au.com.leighton.mytrainings.model.view.common.NonMandatoryTraining_VORow;

import oracle.adf.model.BindingContext;

import oracle.binding.BindingContainer;
import oracle.binding.OperationBinding;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.ViewObject;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.DBTransaction;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 25 11:36:30 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NonMandatoryTraining_VORowImpl extends ViewRowImpl implements NonMandatoryTraining_VORow {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CourseId {
            public Object get(NonMandatoryTraining_VORowImpl obj) {
                return obj.getCourseId();
            }

            public void put(NonMandatoryTraining_VORowImpl obj, Object value) {
                obj.setCourseId((Number)value);
            }
        },
        CourseName {
            public Object get(NonMandatoryTraining_VORowImpl obj) {
                return obj.getCourseName();
            }

            public void put(NonMandatoryTraining_VORowImpl obj, Object value) {
                obj.setCourseName((String)value);
            }
        },
        Url {
            public Object get(NonMandatoryTraining_VORowImpl obj) {
                return obj.getUrl();
            }

            public void put(NonMandatoryTraining_VORowImpl obj, Object value) {
                obj.setUrl((String)value);
            }
        },
        Description {
            public Object get(NonMandatoryTraining_VORowImpl obj) {
                return obj.getDescription();
            }

            public void put(NonMandatoryTraining_VORowImpl obj, Object value) {
                obj.setDescription((String)value);
            }
        },
        CurseDate {
            public Object get(NonMandatoryTraining_VORowImpl obj) {
                return obj.getCurseDate();
            }

            public void put(NonMandatoryTraining_VORowImpl obj, Object value) {
                obj.setCurseDate((Date)value);
            }
        },
        CategoryName {
            public Object get(NonMandatoryTraining_VORowImpl obj) {
                return obj.getCategoryName();
            }

            public void put(NonMandatoryTraining_VORowImpl obj, Object value) {
                obj.setCategoryName((String)value);
            }
        },
        CategoryId {
            public Object get(NonMandatoryTraining_VORowImpl obj) {
                return obj.getCategoryId();
            }

            public void put(NonMandatoryTraining_VORowImpl obj, Object value) {
                obj.setCategoryId((Number)value);
            }
        },
        Mandatory {
            public Object get(NonMandatoryTraining_VORowImpl obj) {
                return obj.getMandatory();
            }

            public void put(NonMandatoryTraining_VORowImpl obj, Object value) {
                obj.setMandatory((String)value);
            }
        },
        MyUserTraininglist_VO1 {
            public Object get(NonMandatoryTraining_VORowImpl obj) {
                return obj.getMyUserTraininglist_VO1();
            }

            public void put(NonMandatoryTraining_VORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(NonMandatoryTraining_VORowImpl object);

        public abstract void put(NonMandatoryTraining_VORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int COURSEID = AttributesEnum.CourseId.index();
    public static final int COURSENAME = AttributesEnum.CourseName.index();
    public static final int URL = AttributesEnum.Url.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int CURSEDATE = AttributesEnum.CurseDate.index();
    public static final int CATEGORYNAME = AttributesEnum.CategoryName.index();
    public static final int CATEGORYID = AttributesEnum.CategoryId.index();
    public static final int MANDATORY = AttributesEnum.Mandatory.index();
    public static final int MYUSERTRAININGLIST_VO1 =
        AttributesEnum.MyUserTraininglist_VO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public NonMandatoryTraining_VORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute CourseId.
     * @return the CourseId
     */
    public Number getCourseId() {
        return (Number)getAttributeInternal(COURSEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CourseId.
     * @param value value to set the  CourseId
     */
    public void setCourseId(Number value) {
        setAttributeInternal(COURSEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CourseName.
     * @return the CourseName
     */
    public String getCourseName() {
        return (String)getAttributeInternal(COURSENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CourseName.
     * @param value value to set the  CourseName
     */
    public void setCourseName(String value) {
        setAttributeInternal(COURSENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Url.
     * @return the Url
     */
    public String getUrl() {
        return (String)getAttributeInternal(URL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Url.
     * @param value value to set the  Url
     */
    public void setUrl(String value) {
        setAttributeInternal(URL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Description.
     * @return the Description
     */
    public String getDescription() {
        return (String)getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Description.
     * @param value value to set the  Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CurseDate.
     * @return the CurseDate
     */
    public Date getCurseDate() {
        return (Date)getAttributeInternal(CURSEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CurseDate.
     * @param value value to set the  CurseDate
     */
    public void setCurseDate(Date value) {
        setAttributeInternal(CURSEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CategoryName.
     * @return the CategoryName
     */
    public String getCategoryName() {
        return (String)getAttributeInternal(CATEGORYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CategoryName.
     * @param value value to set the  CategoryName
     */
    public void setCategoryName(String value) {
        setAttributeInternal(CATEGORYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CategoryId.
     * @return the CategoryId
     */
    public Number getCategoryId() {
        return (Number)getAttributeInternal(CATEGORYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CategoryId.
     * @param value value to set the  CategoryId
     */
    public void setCategoryId(Number value) {
        setAttributeInternal(CATEGORYID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Mandatory.
     * @return the Mandatory
     */
    public String getMandatory() {
        return (String)getAttributeInternal(MANDATORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Mandatory.
     * @param value value to set the  Mandatory
     */
    public void setMandatory(String value) {
        setAttributeInternal(MANDATORY, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> MyUserTraininglist_VO1.
     */
    public RowSet getMyUserTraininglist_VO1() {
        return (RowSet)getAttributeInternal(MYUSERTRAININGLIST_VO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    public void createCourse(Number curseId) {

        String username = EnvironmentUtil.getUsername();
        try {
            RowSet rowsetcreate = getMyUserTraininglist_VO1();
            Row row = rowsetcreate.createRow();
            row.setAttribute("CourseId", curseId);
            row.setAttribute("Username", username);
            rowsetcreate.insertRow(row);
            rowsetcreate.executeQuery();
            this.getDBTransaction().commit();
            DBTransaction bTransaction = getDBTransaction();
            ViewObject vo =
                bTransaction.findViewObject("MyTrainingListCategoryVO1");
            vo.setNamedWhereClauseParam("userName", username);
            vo.executeQuery();
          /*  BindingContainer bindings = getBindings();
            OperationBinding operationBinding =
                bindings.getOperationBinding("getTainingCategorybyList");
            operationBinding.execute();*/

        } catch (Exception e) {
            String message = e.getMessage();
            e.printStackTrace();
               LogUtility.logSevere(EnvironmentUtil.class, message, e);
        }

    }

    public BindingContainer getBindings() {
        return BindingContext.getCurrent().getCurrentBindingsEntry();
    }
}
