package au.com.leicon.socialmedia.services;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

public class SocialMediaComposite_ptClient
{
  @WebServiceRef
  private static Socialmediacomposite_client_ep socialmediacomposite_client_ep;

  public static void main(String [] args)
  {
    socialmediacomposite_client_ep = new Socialmediacomposite_client_ep();
    SocialMediaComposite socialMediaComposite = socialmediacomposite_client_ep.getSocialMediaComposite_pt();
    // Add your code to call the desired methods.
  }
}
