package au.com.leicon.socialmedia.services;

import au.com.leicon.socialmedia.services.types.DataType;
import au.com.leicon.socialmedia.services.types.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 110329.0915.20612)

@WebService(wsdlLocation="http://lclxsoar1u.lc.local:8001/soa-infra/services/default/SocialMediaComposite/socialmediacomposite_client_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/PortalApplication/SocialMediaComposite/SocialMediaComposite",
  name="SocialMediaComposite")
@XmlSeeAlso(
  { ObjectFactory.class })
public interface SocialMediaComposite
{
  @WebMethod(action="process")
  @Action(input="process", output="http://xmlns.oracle.com/PortalApplication/SocialMediaComposite/SocialMediaComposite/SocialMediaComposite/processResponse")
  @ResponseWrapper(localName="processResponse", targetNamespace="http://xmlns.oracle.com/PortalApplication/SocialMediaComposite/SocialMediaComposite",
    className="au.com.leicon.socialmedia.services.types.ProcessResponse")
  @RequestWrapper(localName="process", targetNamespace="http://xmlns.oracle.com/PortalApplication/SocialMediaComposite/SocialMediaComposite",
    className="au.com.leicon.socialmedia.services.types.Process")
  @WebResult(targetNamespace="http://xmlns.oracle.com/PortalApplication/SocialMediaComposite/SocialMediaComposite",
    name="Data")
  public DataType process(@WebParam(targetNamespace="http://xmlns.oracle.com/PortalApplication/SocialMediaComposite/SocialMediaComposite",
      name="site")
    String site, @WebParam(targetNamespace="http://xmlns.oracle.com/PortalApplication/SocialMediaComposite/SocialMediaComposite",
      name="account_id")
    String accountId);
}
