package au.com.leighton.portal.peoplefinder.model.peoplesearch;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

public class PhoSearchPeople_ptClient
{
  @WebServiceRef
  private static Phosearchpeople_client_ep phosearchpeople_client_ep;

  public static void main(String [] args)
  {
    phosearchpeople_client_ep = new Phosearchpeople_client_ep();
    PhoSearchPeople phoSearchPeople = phosearchpeople_client_ep.getPhoSearchPeople_pt();
    // Add your code to call the desired methods.
  }
}
