package au.com.leighton.portal.peoplefinder.model.peoplesearch;

import au.com.leighton.portal.peoplefinder.model.peoplesearch.generated.ObjectFactory;
import au.com.leighton.portal.peoplefinder.model.peoplesearch.generated.PhoSearchOutput;

import java.math.BigDecimal;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebService(wsdlLocation="http://lclxsoa11gdev.lc.local:7001/soa-infra/services/default/PhoSearchPeople/phosearchpeople_client_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchPeople/PhoSearchPeople",
  name="PhoSearchPeople")
@XmlSeeAlso(
  { ObjectFactory.class })
public interface PhoSearchPeople
{
  @WebMethod(action="process")
  @Action(input="process", output="http://xmlns.oracle.com/Portal/PhoSearchPeople/PhoSearchPeople/PhoSearchPeople/processResponse")
  @ResponseWrapper(localName="processResponse", targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchPeople/PhoSearchPeople",
    className="au.com.leighton.portal.peoplefinder.model.peoplesearch.generated.PhoSearchResultOutputCollection")
  @RequestWrapper(localName="process", targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchPeople/PhoSearchPeople",
    className="au.com.leighton.portal.peoplefinder.model.peoplesearch.generated.Process")
  public void process(@WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchPeople/PhoSearchPeople",
      name="SearchType")
    String searchType, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchPeople/PhoSearchPeople",
      name="SimpleSearch")
    String simpleSearch, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchPeople/PhoSearchPeople",
      name="LocationID")
    BigDecimal locationID, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchPeople/PhoSearchPeople",
      name="Surname")
    String surname, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchPeople/PhoSearchPeople",
      name="FirstName")
    String firstName, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchPeople/PhoSearchPeople",
      name="Title")
    String title, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchPeople/PhoSearchPeople",
      name="Dept")
    String dept, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchPeople/PhoSearchPeople",
      name="Location")
    String location, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchPeople/PhoSearchPeople",
      name="BusUnit")
    String busUnit, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchPeople/PhoSearchPeople",
      name="Division")
    String division, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchPeople/PhoSearchPeople",
      name="Phone")
    String phone, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchPeople/PhoSearchPeople",
      name="Mobile")
    String mobile, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchPeople/PhoSearchPeople",
      name="Expertise")
    String expertise, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchPeople/PhoSearchPeople",
      name="NUMFOUND", mode=Mode.OUT)
    Holder<BigDecimal> numfound, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchPeople/PhoSearchPeople",
      name="RESULT", mode=Mode.OUT)
    Holder<String> result, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchPeople/PhoSearchPeople",
      name="PhoSearchOutput", mode=Mode.OUT)
    Holder<List<PhoSearchOutput>> phoSearchOutput);
}
