package au.com.leighton.mytrainingadmin.model.view.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 06 20:02:45 IST 2012
// ---------------------------------------------------------------------
public interface MyTrainingCategory_VORow extends Row {
    void deletCategory(Number CategoryId);
}
