package au.com.leighton.portal.innovation.wcmodel.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 17 13:03:36 EST 2011
// ---------------------------------------------------------------------
public interface AppModuleWcModel extends ApplicationModule
{
    String getEmailForUsername(String username);
}
