package au.com.leighton.portal.innovation.wcmodel.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 17 11:47:50 EST 2011
// ---------------------------------------------------------------------
public interface WcAsActorDetailView extends ViewObject
{
    void setusername(String value);

    String getusername();
}
