package au.com.leighton.portal.innovation.model.client;

import au.com.leighton.portal.innovation.model.FilterBean;
import au.com.leighton.portal.innovation.model.IdeaBean;
import au.com.leighton.portal.innovation.model.InnovationBean;
import au.com.leighton.portal.innovation.model.common.AppModuleModel;

import java.util.List;

import javax.faces.model.SelectItem;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 17 13:18:15 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleModelClient extends ApplicationModuleImpl implements AppModuleModel
{
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleModelClient()
    {
    }

    public void updateInnovation(InnovationBean innovationBean,
                                 String emailAddress)
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"updateInnovation",new String [] {"au.com.leighton.portal.innovation.model.InnovationBean","java.lang.String"},new Object[] {innovationBean, emailAddress});
        return;
    }

    public void storeNewIdea(IdeaBean newIdeaBean, String currentUsername,
                             String emailAddress)
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"storeNewIdea",new String [] {"au.com.leighton.portal.innovation.model.IdeaBean","java.lang.String","java.lang.String"},new Object[] {newIdeaBean, currentUsername, emailAddress});
        return;
    }

    public void storeFilter(FilterBean filterBean, boolean storeIdeaComponents,
                            boolean storeInnovationComponents)
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"storeFilter",new String [] {"au.com.leighton.portal.innovation.model.FilterBean","boolean","boolean"},new Object[] {filterBean, new Boolean(storeIdeaComponents), new Boolean(storeInnovationComponents)});
        return;
    }

    public void processNotAdopt(Number submittedInnovationId, String newStatus,
                                String comment, String emailAddress)
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"processNotAdopt",new String [] {"oracle.jbo.domain.Number","java.lang.String","java.lang.String","java.lang.String"},new Object[] {submittedInnovationId, newStatus, comment, emailAddress});
        return;
    }

    public void processAdopt(IdeaBean ideaBean, InnovationBean innovationBean,
                             String emailAddress)
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"processAdopt",new String [] {"au.com.leighton.portal.innovation.model.IdeaBean","au.com.leighton.portal.innovation.model.InnovationBean","java.lang.String"},new Object[] {ideaBean, innovationBean, emailAddress});
        return;
    }

    public boolean isUserInRoleForDivision(String username,
                                           String divisionName)
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"isUserInRoleForDivision",new String [] {"java.lang.String","java.lang.String"},new Object[] {username, divisionName});
        return ((Boolean)_ret).booleanValue();
    }

    public List<InnovationBean> getInnovationList(String[] categories,
                                                  String[] divisions,
                                                  String[] statuses,
                                                  Date fromDate, Date toDate,
                                                  String ideaSubmittedByUsername)
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"getInnovationList",new String [] {"[Ljava.lang.String;","[Ljava.lang.String;","[Ljava.lang.String;","oracle.jbo.domain.Date","oracle.jbo.domain.Date","java.lang.String"},new Object[] {categories, divisions, statuses, fromDate, toDate, ideaSubmittedByUsername});
        return (List<InnovationBean>)_ret;
    }

    public List<IdeaBean> getIdeaList(String[] divisions, String[] statuses,
                                      Date fromDate, Date toDate)
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"getIdeaList",new String [] {"[Ljava.lang.String;","[Ljava.lang.String;","oracle.jbo.domain.Date","oracle.jbo.domain.Date"},new Object[] {divisions, statuses, fromDate, toDate});
        return (List<IdeaBean>)_ret;
    }

    public FilterBean getFilter(String username)
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"getFilter",new String [] {"java.lang.String"},new Object[] {username});
        return (FilterBean)_ret;
    }

    public List<SelectItem> getDropDownValuesInnovationStatusFilter()
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"getDropDownValuesInnovationStatusFilter",null,null);
        return (List<SelectItem>)_ret;
    }

    public List<SelectItem> getDropDownValuesInnovationStatus()
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"getDropDownValuesInnovationStatus",null,null);
        return (List<SelectItem>)_ret;
    }

    public List<SelectItem> getDropDownValuesInnovationCategoryFilter()
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"getDropDownValuesInnovationCategoryFilter",null,null);
        return (List<SelectItem>)_ret;
    }

    public List<SelectItem> getDropDownValuesIdeaStatusFilter()
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"getDropDownValuesIdeaStatusFilter",null,null);
        return (List<SelectItem>)_ret;
    }

    public List<SelectItem> getDropDownValuesDivisionFilter()
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"getDropDownValuesDivisionFilter",null,null);
        return (List<SelectItem>)_ret;
    }

    public List<SelectItem> getDropDownValuesDivision()
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"getDropDownValuesDivision",null,null);
        return (List<SelectItem>)_ret;
    }

    public List<SelectItem> getDropDownValuesCategory()
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"getDropDownValuesCategory",null,null);
        return (List<SelectItem>)_ret;
    }

    public List<SelectItem> getDropDownValuesBusinessOptimisation()
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"getDropDownValuesBusinessOptimisation",null,null);
        return (List<SelectItem>)_ret;
    }

    public List<SelectItem> getDropDownValuesBenefit()
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"getDropDownValuesBenefit",null,null);
        return (List<SelectItem>)_ret;
    }

    public List<String> getDivisionsForUser(String username)
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"getDivisionsForUser",new String [] {"java.lang.String"},new Object[] {username});
        return (List<String>)_ret;
    }
}
