package au.com.leighton.portal.peoplefinder.model.common;

import au.com.leighton.portal.peoplefinder.model.Response;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 30 11:23:01 EST 2011
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule
{
    Response getSpacesForUserAndRole(String username, String[] validRoles);

    Response getConnectionsForUser(String username);
}
