package au.com.leighton.portal.peoplefinder.model.client;

import au.com.leighton.portal.peoplefinder.model.Response;
import au.com.leighton.portal.peoplefinder.model.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 30 11:23:01 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule
{
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient()
    {
    }

    public Response getSpacesForUserAndRole(String username,
                                            String[] validRoles)
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"getSpacesForUserAndRole",new String [] {"java.lang.String","[Ljava.lang.String;"},new Object[] {username, validRoles});
        return (Response)_ret;
    }

    public Response getConnectionsForUser(String username)
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"getConnectionsForUser",new String [] {"java.lang.String"},new Object[] {username});
        return (Response)_ret;
    }
}
