package au.com.leighton.portal.peoplefinder.model.locationsearch;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

public class PhoSearchLocations_ptClient
{
  @WebServiceRef
  private static Phosearchlocations_client_ep phosearchlocations_client_ep;

  public static void main(String [] args)
  {
    phosearchlocations_client_ep = new Phosearchlocations_client_ep();
    PhoSearchLocations phoSearchLocations = phosearchlocations_client_ep.getPhoSearchLocations_pt();
    // Add your code to call the desired methods.
  }
}
