package au.com.leighton.portal.peoplefinder.model.locationsearch;

import java.math.BigDecimal;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebService(wsdlLocation="http://lclxsoa11gdev.lc.local:7001/soa-infra/services/default/PhoSearchLocations/phosearchlocations_client_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchLocations/PhoSearchLocations",
  name="PhoSearchLocations")
@XmlSeeAlso(
  { au.com.leighton.portal.peoplefinder.model.locationsearch.generated.ObjectFactory.class })
public interface PhoSearchLocations
{
  @WebMethod(action="process")
  @Action(input="process", output="http://xmlns.oracle.com/Portal/PhoSearchLocations/PhoSearchLocations/PhoSearchLocations/processResponse")
  @ResponseWrapper(localName="processResponse", targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchLocations/PhoSearchLocations",
    className="au.com.leighton.portal.peoplefinder.model.locationsearch.generated.PhoSearchResultOutputCollection")
  @RequestWrapper(localName="process", targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchLocations/PhoSearchLocations",
    className="au.com.leighton.portal.peoplefinder.model.locationsearch.generated.Process")
  public void process(@WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchLocations/PhoSearchLocations",
      name="SearchType")
    String searchType, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchLocations/PhoSearchLocations",
      name="SimpleSearch")
    String simpleSearch, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchLocations/PhoSearchLocations",
      name="i_locn")
    String iLocn, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchLocations/PhoSearchLocations",
      name="i_company")
    String iCompany, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchLocations/PhoSearchLocations",
      name="i_suburb")
    String iSuburb, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchLocations/PhoSearchLocations",
      name="i_state")
    String iState, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchLocations/PhoSearchLocations",
      name="i_phone")
    String iPhone, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchLocations/PhoSearchLocations",
      name="i_vpn")
    String iVpn, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchLocations/PhoSearchLocations",
      name="i_notes")
    String iNotes, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchLocations/PhoSearchLocations",
      name="NUMFOUND", mode=Mode.OUT)
    Holder<BigDecimal> numfound, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchLocations/PhoSearchLocations",
      name="RESULT", mode=Mode.OUT)
    Holder<String> result, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoSearchLocations/PhoSearchLocations",
      name="PhoLocation", mode=Mode.OUT)
    Holder<List<au.com.leighton.portal.peoplefinder.model.locationsearch.generated.PhoLocation>> phoLocation);
}
