package au.com.leighton.portal.innovation.wcmodel.client;

import au.com.leighton.portal.innovation.wcmodel.common.AppModuleWcModel;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 17 13:03:36 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleWcModelClient extends ApplicationModuleImpl implements AppModuleWcModel
{
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleWcModelClient()
    {
    }

    public String getEmailForUsername(String username)
    {
        Object _ret =
            this.riInvokeExportedMethod(this,"getEmailForUsername",new String [] {"java.lang.String"},new Object[] {username});
        return (String)_ret;
    }
}
