package au.com.leighton.portal.innovation.wcmodel.client;

import au.com.leighton.portal.innovation.wcmodel.common.WcAsActorDetailView;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 17 11:47:50 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WcAsActorDetailViewClient extends ViewUsageImpl implements WcAsActorDetailView
{
    /**
     * This is the default constructor (do not remove).
     */
    public WcAsActorDetailViewClient()
    {
    }

    public void setusername(String value)
    {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setusername",new String [] {"java.lang.String"},new Object[] {value});
        return;
    }

    public String getusername()
    {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getusername",null,null);
        return (String)_ret;
    }
}
