DROP TABLE "PROF_EXPERIENCE";
CREATE TABLE "PROF_EXPERIENCE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DISPLAYORDER" NUMBER(2,0), 
	"TITLE" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"EXPERIENCEDESCRIPTION" VARCHAR2(2000 CHAR) NOT NULL ENABLE, 
	"DELETED" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "EXPERIENCE_PK" PRIMARY KEY ("ID"));
COMMIT;

DROP SEQUENCE LEIGHTON_SEQUENCE_EXPERIENCE;
CREATE SEQUENCE LEIGHTON_SEQUENCE_EXPERIENCE;
COMMIT;

DROP TABLE "PROF_WORKHISTORY";
CREATE TABLE "PROF_WORKHISTORY" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"ROLE" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"COMPANY" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"LOCATION" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"STARTDATE" DATE NOT NULL ENABLE, 
	"ENDDATE" DATE, 
	"JOBDESCRIPTION" VARCHAR2(2000 CHAR), 
	"DELETED" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "WORKHISTORY_PK" PRIMARY KEY ("ID"));
COMMIT;
DROP SEQUENCE LEIGHTON_SEQUENCE_WORKHISTORY;
CREATE SEQUENCE LEIGHTON_SEQUENCE_WORKHISTORY;
COMMIT;
