package au.com.leighton.portal.profile.model.client;


import au.com.leighton.portal.profile.IExperience;
import au.com.leighton.portal.profile.IExperienceItem;
import au.com.leighton.portal.profile.IWorkHistory;
import au.com.leighton.portal.profile.IWorkHistoryItem;
import au.com.leighton.portal.profile.ProfileResponse;
import au.com.leighton.portal.profile.model.common.AppModule;

import java.util.List;

import oracle.jbo.client.remote.ApplicationModuleImpl;
import oracle.jbo.domain.Date;


// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Aug 01 09:22:00 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule
{
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient()
    {
    }

    public ProfileResponse updateWorkHistoryItem(IWorkHistoryItem original,
                                                 String role, String company,
                                                 String location,
                                                 Date fromDate, Date toDate,
                                                 String jobDescription)
    {
        Object _ret =
            this.riInvokeExportedMethod(this, "updateWorkHistoryItem",
                                        new String[]
                { "au.com.leighton.portal.profile.IWorkHistoryItem",
                  "java.lang.String", "java.lang.String", "java.lang.String",
                  "oracle.jbo.domain.Date", "oracle.jbo.domain.Date",
                  "java.lang.String" }, new Object[]
                { original, role, company, location, fromDate, toDate,
                  jobDescription });
        return (ProfileResponse)_ret;
    }

    public ProfileResponse updateExperienceItem(IExperienceItem original,
                                                String title,
                                                String experienceDescription)
    {
        Object _ret =
            this.riInvokeExportedMethod(this, "updateExperienceItem", new String[]
                { "au.com.leighton.portal.profile.IExperienceItem",
                  "java.lang.String", "java.lang.String" }, new Object[]
                { original, title, experienceDescription });
        return (ProfileResponse)_ret;
    }

    public ProfileResponse getWorkHistory(String username)
    {
        Object _ret =
            this.riInvokeExportedMethod(this, "getWorkHistory", new String[]
                { "java.lang.String" }, new Object[]
                { username });
        return (ProfileResponse)_ret;
    }

    public ProfileResponse getExperience(String username)
    {
        Object _ret =
            this.riInvokeExportedMethod(this, "getExperience", new String[]
                { "java.lang.String" }, new Object[]
                { username });
        return (ProfileResponse)_ret;
    }

    public List<IWorkHistoryItem> getAllWorkHistoryItems()
    {
        Object _ret =
            this.riInvokeExportedMethod(this, "getAllWorkHistoryItems", null,
                                        null);
        return (List<IWorkHistoryItem>)_ret;
    }

    public List<IExperienceItem> getAllExperienceItems()
    {
        Object _ret =
            this.riInvokeExportedMethod(this, "getAllExperienceItems", null,
                                        null);
        return (List<IExperienceItem>)_ret;
    }

    public ProfileResponse deleteWorkHistoryItem(IWorkHistory workHistory,
                                                 IWorkHistoryItem workHistoryItem)
    {
        Object _ret =
            this.riInvokeExportedMethod(this, "deleteWorkHistoryItem",
                                        new String[]
                { "au.com.leighton.portal.profile.IWorkHistory",
                  "au.com.leighton.portal.profile.IWorkHistoryItem" },
                new Object[]
                { workHistory, workHistoryItem });
        return (ProfileResponse)_ret;
    }

    public ProfileResponse deleteExperienceItem(IExperience experience,
                                                IExperienceItem experienceItem)
    {
        Object _ret =
            this.riInvokeExportedMethod(this, "deleteExperienceItem", new String[]
                { "au.com.leighton.portal.profile.IExperience",
                  "au.com.leighton.portal.profile.IExperienceItem" },
                new Object[]
                { experience, experienceItem });
        return (ProfileResponse)_ret;
    }

    public ProfileResponse createWorkHistoryItem(IWorkHistory workHistory,
                                                 String role, String company,
                                                 String location,
                                                 Date fromDate, Date toDate,
                                                 String jobDescription)
    {
        Object _ret =
            this.riInvokeExportedMethod(this, "createWorkHistoryItem",
                                        new String[]
                { "au.com.leighton.portal.profile.IWorkHistory",
                  "java.lang.String", "java.lang.String", "java.lang.String",
                  "oracle.jbo.domain.Date", "oracle.jbo.domain.Date",
                  "java.lang.String" }, new Object[]
                { workHistory, role, company, location, fromDate, toDate,
                  jobDescription });
        return (ProfileResponse)_ret;
    }

    public ProfileResponse createExperienceItem(IExperience experience,
                                                String title,
                                                String experienceDescription)
    {
        Object _ret =
            this.riInvokeExportedMethod(this, "createExperienceItem", new String[]
                { "au.com.leighton.portal.profile.IExperience",
                  "java.lang.String", "java.lang.String" }, new Object[]
                { experience, title, experienceDescription });
        return (ProfileResponse)_ret;
    }
}
