CREATE TABLE  "MYLINKS" 
   (	"MYLINKS_ID" NUMBER NOT NULL ENABLE, 
	"DISPLAYNAME" VARCHAR2(150) NOT NULL ENABLE, 
	"URL" VARCHAR2(250) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(50) NOT NULL ENABLE, 
	"NEWPAGE" VARCHAR2(3), 
	 CONSTRAINT "MYLINKS_PK" PRIMARY KEY ("MYLINKS_ID") ENABLE
   ) ;



CREATE SEQUENCE   "MYLINKS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;



CREATE OR REPLACE TRIGGER  "BI_MYLINKS" 
  before insert on "MYLINKS"               
  for each row  
begin   
  if :NEW."MYLINKS_ID" is null then 
    select "MYLINKS_SEQ".nextval into :NEW."MYLINKS_ID" from dual; 
  end if; 
end; 