package au.com.leighton.portal.peoplefinder.model.locationdetail;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebServiceClient(wsdlLocation="http://lclxsoa11gdev.lc.local:7001/soa-infra/services/default/PhoGetLocationDetail/phogetlocationdetail_client_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/Portal/PhoGetLocationDetail/PhoGetLocationDetail",
  name="phogetlocationdetail_client_ep")
public class Phogetlocationdetail_client_ep
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("au.com.leighton.portal.peoplefinder.model.locationdetail.Phogetlocationdetail_client_ep");
      URL baseUrl = Phogetlocationdetail_client_ep.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            Phogetlocationdetail_client_ep.class.getResource("http://lclxsoa11gdev.lc.local:7001/soa-infra/services/default/PhoGetLocationDetail/phogetlocationdetail_client_ep?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://lclxsoa11gdev.lc.local:7001/soa-infra/services/default/PhoGetLocationDetail/phogetlocationdetail_client_ep?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://lclxsoa11gdev.lc.local:7001/soa-infra/services/default/PhoGetLocationDetail/phogetlocationdetail_client_ep?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://lclxsoa11gdev.lc.local:7001/soa-infra/services/default/PhoGetLocationDetail/phogetlocationdetail_client_ep?WSDL",
          e);
    }
  }

  public Phogetlocationdetail_client_ep()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/Portal/PhoGetLocationDetail/PhoGetLocationDetail",
                    "phogetlocationdetail_client_ep"));
  }

  public Phogetlocationdetail_client_ep(URL wsdlLocation,
                                        QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="PhoGetLocationDetail_pt")
  public au.com.leighton.portal.peoplefinder.model.locationdetail.PhoGetLocationDetail getPhoGetLocationDetail_pt()
  {
    return (au.com.leighton.portal.peoplefinder.model.locationdetail.PhoGetLocationDetail) super.getPort(new QName("http://xmlns.oracle.com/Portal/PhoGetLocationDetail/PhoGetLocationDetail",
                                                                                                                   "PhoGetLocationDetail_pt"),
                                                                                                         au.com.leighton.portal.peoplefinder.model.locationdetail.PhoGetLocationDetail.class);
  }

  @WebEndpoint(name="PhoGetLocationDetail_pt")
  public au.com.leighton.portal.peoplefinder.model.locationdetail.PhoGetLocationDetail getPhoGetLocationDetail_pt(WebServiceFeature... features)
  {
    return (au.com.leighton.portal.peoplefinder.model.locationdetail.PhoGetLocationDetail) super.getPort(new QName("http://xmlns.oracle.com/Portal/PhoGetLocationDetail/PhoGetLocationDetail",
                                                                                                                   "PhoGetLocationDetail_pt"),
                                                                                                         au.com.leighton.portal.peoplefinder.model.locationdetail.PhoGetLocationDetail.class,
                                                                                                         features);
  }
}
