package au.com.leighton.portal.peoplefinder.model.locationdetail;

import java.math.BigDecimal;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebService(wsdlLocation="http://lclxsoa11gdev.lc.local:7001/soa-infra/services/default/PhoGetLocationDetail/phogetlocationdetail_client_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/Portal/PhoGetLocationDetail/PhoGetLocationDetail",
  name="PhoGetLocationDetail")
@XmlSeeAlso(
  { au.com.leighton.portal.peoplefinder.model.locationdetail.generated.ObjectFactory.class })
public interface PhoGetLocationDetail
{
  @WebMethod(action="process")
  @Action(input="process", output="http://xmlns.oracle.com/Portal/PhoGetLocationDetail/PhoGetLocationDetail/PhoGetLocationDetail/processResponse")
  @ResponseWrapper(localName="processResponse", targetNamespace="http://xmlns.oracle.com/Portal/PhoGetLocationDetail/PhoGetLocationDetail",
    className="au.com.leighton.portal.peoplefinder.model.locationdetail.generated.PhoGetLocationDetailCollection")
  @RequestWrapper(localName="process", targetNamespace="http://xmlns.oracle.com/Portal/PhoGetLocationDetail/PhoGetLocationDetail",
    className="au.com.leighton.portal.peoplefinder.model.locationdetail.generated.Process")
  public void process(@WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoGetLocationDetail/PhoGetLocationDetail",
      name="i_location_id")
    BigDecimal iLocationId, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoGetLocationDetail/PhoGetLocationDetail",
      name="RESULT", mode=Mode.OUT)
    Holder<String> result, @WebParam(targetNamespace="http://xmlns.oracle.com/Portal/PhoGetLocationDetail/PhoGetLocationDetail",
      name="PhoLocation", mode=Mode.OUT)
    Holder<List<au.com.leighton.portal.peoplefinder.model.locationdetail.generated.PhoGetLocationDetailOutput>> phoLocation);
}
