package au.com.leighton.portal.innovation.model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 17 11:51:06 EST 2011
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InnoDivisionsViewImpl extends ViewObjectImpl
{
    /**
     * This is the default constructor (do not remove).
     */
    public InnoDivisionsViewImpl()
    {
    }
}
