package au.com.leighton.mytrainings.model.view.client;

import au.com.leighton.mytrainings.model.view.common.MyTrainingListCategoryVO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 24 18:34:40 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MyTrainingListCategoryVOClient extends ViewUsageImpl implements MyTrainingListCategoryVO {
    /**
     * This is the default constructor (do not remove).
     */
    public MyTrainingListCategoryVOClient() {
    }

    public void getTainingCategorybyList() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getTainingCategorybyList",null,null);
        return;
    }
}
