package au.com.leighton.mytrainings.model.view.client;

import au.com.leighton.mytrainings.model.view.common.MyTrainingList_VO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu May 24 18:49:10 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MyTrainingList_VOClient extends ViewUsageImpl implements MyTrainingList_VO {
    /**
     * This is the default constructor (do not remove).
     */
    public MyTrainingList_VOClient() {
    }

    public void getMyTrainingList() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getMyTrainingList",null,null);
        return;
    }
}
