package au.com.leighton.mytrainings.model.view.client;

import au.com.leighton.mytrainings.model.view.common.MyTrainingListCategoryVORow;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 23 16:46:32 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MyTrainingListCategoryVORowClient extends RowImpl implements MyTrainingListCategoryVORow {
    /**
     * This is the default constructor (do not remove).
     */
    public MyTrainingListCategoryVORowClient() {
    }


    public void deleteCourse(Number curseId) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"deleteCourse",new String [] {"oracle.jbo.domain.Number"},new Object[] {curseId});
        return;
    }
}
