package au.com.leighton.mytrainings.model.view.client;

import au.com.leighton.mytrainings.model.view.common.NonMandatoryTraining_VORow;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 25 12:13:44 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NonMandatoryTraining_VORowClient extends RowImpl implements NonMandatoryTraining_VORow {
    /**
     * This is the default constructor (do not remove).
     */
    public NonMandatoryTraining_VORowClient() {
    }

    public void createCourse(Number curseId) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"createCourse",new String [] {"oracle.jbo.domain.Number"},new Object[] {curseId});
        return;
    }
}
