package au.com.leighton.mytrainings.model.view.client;

import au.com.leighton.mytrainings.model.view.common.NonMandatoryTraining_VO;

import oracle.jbo.client.remote.ViewUsageImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 29 20:25:41 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NonMandatoryTraining_VOClient extends ViewUsageImpl implements NonMandatoryTraining_VO {
    /**
     * This is the default constructor (do not remove).
     */
    public NonMandatoryTraining_VOClient() {
    }

    public void getNonMandatoryList() {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"getNonMandatoryList",null,null);
        return;
    }
}
