package au.com.leighton.mytrainingadmin.model.view.client;

import au.com.leighton.mytrainingadmin.model.view.common.MyTrainingCategory_VORow;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Number;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 06 20:02:45 IST 2012
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MyTrainingCategory_VORowClient extends RowImpl implements MyTrainingCategory_VORow {
    /**
     * This is the default constructor (do not remove).
     */
    public MyTrainingCategory_VORowClient() {
    }

    public void deletCategory(Number CategoryId) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"deletCategory",new String [] {"oracle.jbo.domain.Number"},new Object[] {CategoryId});
        return;
    }
}
