package au.com.leighton.portal.application.uat;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 101221.1153.15811)

@WebServiceClient(wsdlLocation="http://portalpsup2.lc.local:7777/soa-infra/services/default/EAgetAppsList/EAgetAppsList_2?WSDL",
  targetNamespace="http://xmlns.oracle.com/Portal/EAgetAppsList/EAgetAppsList",
  name="EAgetAppsList")
public class EAgetAppsList
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("au.com.leighton.portal.application.uat.EAgetAppsList");
      URL baseUrl = EAgetAppsList.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            EAgetAppsList.class.getResource("http://portalpsup2.lc.local:7777/soa-infra/services/default/EAgetAppsList/EAgetAppsList_2?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://portalpsup2.lc.local:7777/soa-infra/services/default/EAgetAppsList/EAgetAppsList_2?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://portalpsup2.lc.local:7777/soa-infra/services/default/EAgetAppsList/EAgetAppsList_2?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://portalpsup2.lc.local:7777/soa-infra/services/default/EAgetAppsList/EAgetAppsList_2?WSDL",
          e);
    }
  }

  public EAgetAppsList()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/Portal/EAgetAppsList/EAgetAppsList",
                    "EAgetAppsList"));
  }

  public EAgetAppsList(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="execute_pt")
  public Execute_ptt getExecute_pt()
  {
    return (Execute_ptt) super.getPort(new QName("http://xmlns.oracle.com/Portal/EAgetAppsList/EAgetAppsList",
                                                 "execute_pt"),
                                       Execute_ptt.class);
  }

  @WebEndpoint(name="execute_pt")
  public Execute_ptt getExecute_pt(WebServiceFeature... features)
  {
    return (Execute_ptt) super.getPort(new QName("http://xmlns.oracle.com/Portal/EAgetAppsList/EAgetAppsList",
                                                 "execute_pt"),
                                       Execute_ptt.class, features);
  }
}
