package au.com.leighton.myspaces.model.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon May 14 17:00:28 IST 2012
// ---------------------------------------------------------------------
public interface MySpacesListVO extends ViewObject {
    void getMySpaceLists(String username);
}
